{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "Coverage reporting using the Cython plugin does not work for the 5.x series of coverage.py. For example, attempting to run coverage tests on [raysect](https://github.com/raysect/source) produces errors:\r\n```bash\r\npython setup.py build_ext -j4 --inplace --line-profile\r\ncoverage run -m unittest discover\r\n```\r\nOutput:\r\n```\r\n...................................................................................................................................................................................................................................................................................................................................................................................................................................................\r\n----------------------------------------------------------------------\r\nRan 435 tests in 2.122s\r\n\r\nOK\r\nCan't add file tracer data for unmeasured file '/home/jlovell/FUN/cherab/raysect/raysect/core/math/_vec3.pxd'\r\n```\r\n\r\nAttempting to produce HTML output also results in an error:\r\n```bash\r\ncoverage html\r\n```\r\n\r\nOutput:\r\n```\r\nCouldn't parse '/home/jlovell/FUN/cherab/raysect/raysect/core/acceleration/accelerator.pyx' as Python source: 'invalid syntax' at line 32\r\n```\r\n\r\nUsing coverage.py 4.5 on the same set of build files results in no errors reported about pyx files, and the HTML output is produced successfully.",
    "closed_at": "2023-01-27T22:01:24Z",
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Thanks for the report. Could be some change in the plugin API. Any investigation welcome.",
            "created_at": "2020-04-14T18:08:21Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-613595569",
            "id": 613595569,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "MDEyOklzc3VlQ29tbWVudDYxMzU5NTU2OQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/613595569/reactions"
            },
            "updated_at": "2020-04-14T18:08:21Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/613595569",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "I ran into a similar issue, but with different exceptions being raised...\r\n\r\nOutput from [this build](https://github.com/nocarryr/cython-sounddevice/runs/583882321) shows an exception raised when trying to add a `FileTracer` for a .pxd\r\n\r\nNo issues after [constraining coverage.py to 4.5.x](https://github.com/nocarryr/cython-sounddevice/runs/586143014) and it seems there are a LOT of changes:\r\nhttps://coverage.readthedocs.io/en/coverage-5.1/whatsnew5x.html\r\n\r\n<details>\r\n<summary>Log output from py.test</summary>\r\n<pre>\r\n Traceback (most recent call last):\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/main.py\", line 191, in wrap_session\r\n     session.exitstatus = doit(config, session) or 0\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/main.py\", line 247, in _main\r\n     config.hook.pytest_runtestloop(session=session)\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/hooks.py\", line 286, in __call__\r\n     return self._hookexec(self, self.get_hookimpls(), kwargs)\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/manager.py\", line 93, in _hookexec\r\n     return self._inner_hookexec(hook, methods, kwargs)\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/manager.py\", line 87, in <lambda>\r\n     firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/callers.py\", line 203, in _multicall\r\n     gen.send(outcome)\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytest_cov/plugin.py\", line 254, in pytest_runtestloop\r\n     self.cov_controller.finish()\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytest_cov/engine.py\", line 197, in finish\r\n     self.cov.stop()\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/control.py\", line 649, in save\r\n     data = self.get_data()\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/control.py\", line 703, in get_data\r\n     if self._collector and self._collector.flush_data():\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/collector.py\", line 426, in flush_data\r\n     self.covdata.add_file_tracers(self.mapped_file_dict(self.file_tracers))\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/sqldata.py\", line 516, in add_file_tracers\r\n     \"Can't add file tracer data for unmeasured file '%s'\" % (filename,)\r\n coverage.misc.CoverageException: Can't add file tracer data for unmeasured file '/home/travis/build/nocarryr/cython-sounddevice/cysounddevice/devices.pxd'\r\n</pre>\r\n</details>\r\n",
            "created_at": "2020-04-14T20:43:02Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-613671329",
            "id": 613671329,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "MDEyOklzc3VlQ29tbWVudDYxMzY3MTMyOQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/613671329/reactions"
            },
            "updated_at": "2020-04-14T20:43:02Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/613671329",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1625941?v=4",
                "events_url": "https://api.github.com/users/nocarryr/events{/privacy}",
                "followers_url": "https://api.github.com/users/nocarryr/followers",
                "following_url": "https://api.github.com/users/nocarryr/following{/other_user}",
                "gists_url": "https://api.github.com/users/nocarryr/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/nocarryr",
                "id": 1625941,
                "login": "nocarryr",
                "node_id": "MDQ6VXNlcjE2MjU5NDE=",
                "organizations_url": "https://api.github.com/users/nocarryr/orgs",
                "received_events_url": "https://api.github.com/users/nocarryr/received_events",
                "repos_url": "https://api.github.com/users/nocarryr/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/nocarryr/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/nocarryr/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/nocarryr"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "I'm curious if it's related to https://github.com/cython/cython/issues/3636",
            "created_at": "2020-05-28T20:34:36Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-635592415",
            "id": 635592415,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "MDEyOklzc3VlQ29tbWVudDYzNTU5MjQxNQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/635592415/reactions"
            },
            "updated_at": "2020-05-28T20:34:36Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/635592415",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/578543?v=4",
                "events_url": "https://api.github.com/users/webknjaz/events{/privacy}",
                "followers_url": "https://api.github.com/users/webknjaz/followers",
                "following_url": "https://api.github.com/users/webknjaz/following{/other_user}",
                "gists_url": "https://api.github.com/users/webknjaz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/webknjaz",
                "id": 578543,
                "login": "webknjaz",
                "node_id": "MDQ6VXNlcjU3ODU0Mw==",
                "organizations_url": "https://api.github.com/users/webknjaz/orgs",
                "received_events_url": "https://api.github.com/users/webknjaz/received_events",
                "repos_url": "https://api.github.com/users/webknjaz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/webknjaz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/webknjaz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/webknjaz"
            }
        },
        {
            "author_association": "NONE",
            "body": "@webknjaz since neither of the projects linked to above use `src/` layout, I'd think not. That issue though and your PR are something I'm sure I'll run up against in other projects so I'll have to keep an eye on it, so thank you for pointing it out ",
            "created_at": "2020-05-29T15:08:28Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-636025928",
            "id": 636025928,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "MDEyOklzc3VlQ29tbWVudDYzNjAyNTkyOA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/636025928/reactions"
            },
            "updated_at": "2020-05-29T15:08:28Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/636025928",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1625941?v=4",
                "events_url": "https://api.github.com/users/nocarryr/events{/privacy}",
                "followers_url": "https://api.github.com/users/nocarryr/followers",
                "following_url": "https://api.github.com/users/nocarryr/following{/other_user}",
                "gists_url": "https://api.github.com/users/nocarryr/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/nocarryr",
                "id": 1625941,
                "login": "nocarryr",
                "node_id": "MDQ6VXNlcjE2MjU5NDE=",
                "organizations_url": "https://api.github.com/users/nocarryr/orgs",
                "received_events_url": "https://api.github.com/users/nocarryr/received_events",
                "repos_url": "https://api.github.com/users/nocarryr/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/nocarryr/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/nocarryr/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/nocarryr"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "Getting this on pandas too.  Traceback follows:\r\n\r\n```\r\nINTERNALERROR> Traceback (most recent call last):\r\nINTERNALERROR>   File \"~/.local/lib/python3.6/site-packages/_pytest/main.py\", line 191, in wrap_session\r\nINTERNALERROR>     session.exitstatus = doit(config, session) or 0\r\nINTERNALERROR>   File \"~/.local/lib/python3.6/site-packages/_pytest/main.py\", line 247, in _main\r\nINTERNALERROR>     config.hook.pytest_runtestloop(session=session)\r\nINTERNALERROR>   File \"~/.local/lib/python3.6/site-packages/pluggy/hooks.py\", line 289, in __call__\r\nINTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)\r\nINTERNALERROR>   File \"~/.local/lib/python3.6/site-packages/pluggy/manager.py\", line 87, in _hookexec\r\nINTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)\r\nINTERNALERROR>   File \"~/.local/lib/python3.6/site-packages/pluggy/manager.py\", line 81, in <lambda>\r\nINTERNALERROR>     firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,\r\nINTERNALERROR>   File \"~/.local/lib/python3.6/site-packages/pluggy/callers.py\", line 203, in _multicall\r\nINTERNALERROR>     gen.send(outcome)\r\nINTERNALERROR>   File \"~/.local/lib/python3.6/site-packages/pytest_cov/plugin.py\", line 254, in pytest_runtestloop\r\nINTERNALERROR>     self.cov_controller.finish()\r\nINTERNALERROR>   File \"~/.local/lib/python3.6/site-packages/pytest_cov/engine.py\", line 197, in finish\r\nINTERNALERROR>     self.cov.stop()\r\nINTERNALERROR>   File \"~/.local/lib/python3.6/site-packages/coverage/control.py\", line 642, in save\r\nINTERNALERROR>     data = self.get_data()\r\nINTERNALERROR>   File \"~/.local/lib/python3.6/site-packages/coverage/control.py\", line 696, in get_data\r\nINTERNALERROR>     if self._collector and self._collector.flush_data():\r\nINTERNALERROR>   File \"~/.local/lib/python3.6/site-packages/coverage/collector.py\", line 426, in flush_data\r\nINTERNALERROR>     self.covdata.add_file_tracers(self.mapped_file_dict(self.file_tracers))\r\nINTERNALERROR>   File \"~/.local/lib/python3.6/site-packages/coverage/sqldata.py\", line 516, in add_file_tracers\r\nINTERNALERROR>     \"Can't add file tracer data for unmeasured file '%s'\" % (filename,)\r\nINTERNALERROR> coverage.misc.CoverageException: Can't add file tracer data for unmeasured file 'pandas/_libs/tslibs/offsets.pxd'\r\n```\r\n\r\nSame exception (on the same file) if I run only a subset of the tests.  There's nothing all that special about offsets.pxd:\r\n\r\n```\r\nfrom numpy cimport int64_t\r\n\r\ncpdef to_offset(object obj)\r\ncdef bint is_offset_object(object obj)\r\ncdef bint is_tick_object(object obj)\r\n\r\ncdef class BaseOffset:\r\n    cdef readonly:\r\n        int64_t n\r\n        bint normalize\r\n        dict _cache\r\n```\r\n\r\nSince the traceback says this file is unmeasured, I tried adding\r\n\r\n```\r\ncdef inline foo():\r\n    return \"bar\"\r\n```\r\n\r\nand that appeared to solve the issue (with a run on a small subset of tests at least).  So this appears to be related to [this](https://groups.google.com/forum/#!searchin/cython-users/coverage%7Csort:date/cython-users/e80vdI9G_3w/Aqn0KRfdBAAJ) issue reported on the mailing list (i didnt find a GH issue) where function/class definition lines are not counted as being covered.",
            "created_at": "2020-06-19T00:43:06Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-646374155",
            "id": 646374155,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "MDEyOklzc3VlQ29tbWVudDY0NjM3NDE1NQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/646374155/reactions"
            },
            "updated_at": "2020-06-19T00:43:06Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/646374155",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/8078968?v=4",
                "events_url": "https://api.github.com/users/jbrockmendel/events{/privacy}",
                "followers_url": "https://api.github.com/users/jbrockmendel/followers",
                "following_url": "https://api.github.com/users/jbrockmendel/following{/other_user}",
                "gists_url": "https://api.github.com/users/jbrockmendel/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jbrockmendel",
                "id": 8078968,
                "login": "jbrockmendel",
                "node_id": "MDQ6VXNlcjgwNzg5Njg=",
                "organizations_url": "https://api.github.com/users/jbrockmendel/orgs",
                "received_events_url": "https://api.github.com/users/jbrockmendel/received_events",
                "repos_url": "https://api.github.com/users/jbrockmendel/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jbrockmendel/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jbrockmendel"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "Update: adding the inline function in offsets.pxd just pushed the problem into another declaration-only .pxd file ",
            "created_at": "2020-06-19T21:27:56Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-646866686",
            "id": 646866686,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "MDEyOklzc3VlQ29tbWVudDY0Njg2NjY4Ng==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/646866686/reactions"
            },
            "updated_at": "2020-06-19T21:27:56Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/646866686",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/8078968?v=4",
                "events_url": "https://api.github.com/users/jbrockmendel/events{/privacy}",
                "followers_url": "https://api.github.com/users/jbrockmendel/followers",
                "following_url": "https://api.github.com/users/jbrockmendel/following{/other_user}",
                "gists_url": "https://api.github.com/users/jbrockmendel/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jbrockmendel",
                "id": 8078968,
                "login": "jbrockmendel",
                "node_id": "MDQ6VXNlcjgwNzg5Njg=",
                "organizations_url": "https://api.github.com/users/jbrockmendel/orgs",
                "received_events_url": "https://api.github.com/users/jbrockmendel/received_events",
                "repos_url": "https://api.github.com/users/jbrockmendel/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jbrockmendel/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jbrockmendel"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "1) We need to add a test case for this.\r\n2) There's probably some kind of special-casing that we need to do for `.pxd` files in the plugin. Or maybe always process all Cython files, even without a corresponding `.c` file. Or something along those lines.",
            "created_at": "2020-06-19T21:42:43Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-646870790",
            "id": 646870790,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "MDEyOklzc3VlQ29tbWVudDY0Njg3MDc5MA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/646870790/reactions"
            },
            "updated_at": "2020-06-19T21:42:43Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/646870790",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "I can report this issue remains with Cython `3.0a7` and coverage `5.5`.",
            "created_at": "2021-05-26T01:59:10Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-848398361",
            "id": 848398361,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "MDEyOklzc3VlQ29tbWVudDg0ODM5ODM2MQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/848398361/reactions"
            },
            "updated_at": "2021-05-26T01:59:10Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/848398361",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/22510164?v=4",
                "events_url": "https://api.github.com/users/cjdsellers/events{/privacy}",
                "followers_url": "https://api.github.com/users/cjdsellers/followers",
                "following_url": "https://api.github.com/users/cjdsellers/following{/other_user}",
                "gists_url": "https://api.github.com/users/cjdsellers/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/cjdsellers",
                "id": 22510164,
                "login": "cjdsellers",
                "node_id": "MDQ6VXNlcjIyNTEwMTY0",
                "organizations_url": "https://api.github.com/users/cjdsellers/orgs",
                "received_events_url": "https://api.github.com/users/cjdsellers/received_events",
                "repos_url": "https://api.github.com/users/cjdsellers/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/cjdsellers/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/cjdsellers/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/cjdsellers"
            }
        },
        {
            "author_association": "NONE",
            "body": "Just tested with Cython `3.0a9` and coverage `6.0`. The issue remains.\r\n\r\nSomething I didn't notice last time I visited the issue was [this workaround](https://github.com/nedbat/coveragepy/issues/972#issuecomment-889746404) linked by @jbrockmendel above.\r\n\r\nOur codebase has over 100 .pxd files with `readonly` members (no public), so will hold off on that for now.",
            "created_at": "2021-10-06T11:28:59Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-936051331",
            "id": 936051331,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc43ywKD",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/936051331/reactions"
            },
            "updated_at": "2021-10-06T11:28:59Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/936051331",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/22510164?v=4",
                "events_url": "https://api.github.com/users/cjdsellers/events{/privacy}",
                "followers_url": "https://api.github.com/users/cjdsellers/followers",
                "following_url": "https://api.github.com/users/cjdsellers/following{/other_user}",
                "gists_url": "https://api.github.com/users/cjdsellers/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/cjdsellers",
                "id": 22510164,
                "login": "cjdsellers",
                "node_id": "MDQ6VXNlcjIyNTEwMTY0",
                "organizations_url": "https://api.github.com/users/cjdsellers/orgs",
                "received_events_url": "https://api.github.com/users/cjdsellers/received_events",
                "repos_url": "https://api.github.com/users/cjdsellers/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/cjdsellers/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/cjdsellers/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/cjdsellers"
            }
        },
        {
            "author_association": "NONE",
            "body": "still encountering this issue with Cython 3.0.0a10 and coverage 6.3.1. any progress/ideas here?",
            "created_at": "2022-02-18T20:17:55Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1045126433",
            "id": 1045126433,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc4-S10h",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1045126433/reactions"
            },
            "updated_at": "2022-02-18T20:17:55Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1045126433",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1345878?v=4",
                "events_url": "https://api.github.com/users/Timtam/events{/privacy}",
                "followers_url": "https://api.github.com/users/Timtam/followers",
                "following_url": "https://api.github.com/users/Timtam/following{/other_user}",
                "gists_url": "https://api.github.com/users/Timtam/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Timtam",
                "id": 1345878,
                "login": "Timtam",
                "node_id": "MDQ6VXNlcjEzNDU4Nzg=",
                "organizations_url": "https://api.github.com/users/Timtam/orgs",
                "received_events_url": "https://api.github.com/users/Timtam/received_events",
                "repos_url": "https://api.github.com/users/Timtam/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Timtam/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Timtam/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Timtam"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "According to my [last comment](https://github.com/cython/cython/issues/3515#issuecomment-646870790), this needs a) a test and b) more investigation following that.\r\n\r\nUnsurprisingly, someone has to do something in order to resolve this issue.",
            "created_at": "2022-02-18T22:16:04Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1045265491",
            "id": 1045265491,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc4-TXxT",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1045265491/reactions"
            },
            "updated_at": "2022-02-18T22:16:04Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1045265491",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "obviously, I don't have enough experience with coverage and/or Cython's internals unfortunately, but if you need any kind of help with debugging, let me know and i'll get back to you asap.",
            "created_at": "2022-02-18T22:38:46Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1045288624",
            "id": 1045288624,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc4-Tdaw",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1045288624/reactions"
            },
            "updated_at": "2022-02-18T22:38:46Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1045288624",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1345878?v=4",
                "events_url": "https://api.github.com/users/Timtam/events{/privacy}",
                "followers_url": "https://api.github.com/users/Timtam/followers",
                "following_url": "https://api.github.com/users/Timtam/following{/other_user}",
                "gists_url": "https://api.github.com/users/Timtam/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Timtam",
                "id": 1345878,
                "login": "Timtam",
                "node_id": "MDQ6VXNlcjEzNDU4Nzg=",
                "organizations_url": "https://api.github.com/users/Timtam/orgs",
                "received_events_url": "https://api.github.com/users/Timtam/received_events",
                "repos_url": "https://api.github.com/users/Timtam/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Timtam/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Timtam/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Timtam"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Debugging is really what is needed here. At some point, either coverage or the plugin in `Cython.Coverage` take a wrong decision about the file, the function, or the coverage data. Once that point is found, there's probably a way to fix it.",
            "created_at": "2022-02-19T13:06:38Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1046013862",
            "id": 1046013862,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc4-WOem",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1046013862/reactions"
            },
            "updated_at": "2022-02-19T13:06:38Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1046013862",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "OK, I took some time to look into this issue from the Cython point of view by getting into Cython.Coverage and think that I got a pretty good feeling about what this plugin does/should do. I started to debug a little further and thats what I found out so far, maybe it will help someone else to track the problem down later. Let's consider this a progress report on my findings up to this point.\r\n\r\nAs far as my debugging goes, the file_tracer method of Cython.Coverage.Plugin never returns an actual file tracer object to coverage.py right now, at least not in my specific constellation. Furthermore, it only gets called with .py files from site packages like pytest and such, but never with a single file from the package that I told it to actually measure. I literally don't know where coverage gets the idea of a .pxd file from, because Cython.Coverage doesn't seem to get in contact with any of these, or I didn't find the function yet where this is supposed to happen. I'll probably see if I can further debug something from the coverage side of things, but the situation as it stands right now leaves me rather clueless. Coverage.py however thinks that .pxd files are associated to Cython.Coverage.Plugin, so that seems to be fine so far.",
            "created_at": "2022-02-19T17:38:56Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1046069169",
            "id": 1046069169,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc4-Wb-x",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 2,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1046069169/reactions"
            },
            "updated_at": "2022-02-19T17:38:56Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1046069169",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1345878?v=4",
                "events_url": "https://api.github.com/users/Timtam/events{/privacy}",
                "followers_url": "https://api.github.com/users/Timtam/followers",
                "following_url": "https://api.github.com/users/Timtam/following{/other_user}",
                "gists_url": "https://api.github.com/users/Timtam/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Timtam",
                "id": 1345878,
                "login": "Timtam",
                "node_id": "MDQ6VXNlcjEzNDU4Nzg=",
                "organizations_url": "https://api.github.com/users/Timtam/orgs",
                "received_events_url": "https://api.github.com/users/Timtam/received_events",
                "repos_url": "https://api.github.com/users/Timtam/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Timtam/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Timtam/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Timtam"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "So, coverage.py doesn't know about .pyx or .pxd files. It just sees the tracing data that comes in, and the executed files that get reported. The Cython tracer should report the source files when an extension module is executed, and in order to do that, it reads the .c file that Cython has generated, and parses the original Cython source files and line numbers from it (they are stored there in C comments). These original source files are then reported to coverage.py. That should include any executable code generated from .pxd files.\r\n\r\nAt least, that's how it used to work when this code was written, for coverage.py < 5.",
            "created_at": "2022-02-25T07:59:05Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1050620261",
            "id": 1050620261,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc4-nzFl",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1050620261/reactions"
            },
            "updated_at": "2022-02-25T07:59:05Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1050620261",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "Yeah, that's what I thought was supposed to happen. As far as my debugging goes however, the Cython Tracer never gets to work. All it gets to do is analyze alot of py files (mainly site packages) and skipping them, for obvious reasons. The issue might also be related to my context, but I can't find the reason why coverage doesn't ask Cython to actually trace my project files as it's supposed to do. I however had to delay my investigation due to other projects taking priority right now. Will hopefully come back to it ASAP. I also opened an issue over at the coverage.py issue tracker, maybe they can tell me specifically what they've changed back in coverage 5.0 when the plugin first stopped working.",
            "created_at": "2022-02-25T08:04:12Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1050623583",
            "id": 1050623583,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc4-nz5f",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1050623583/reactions"
            },
            "updated_at": "2022-02-25T08:04:12Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1050623583",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1345878?v=4",
                "events_url": "https://api.github.com/users/Timtam/events{/privacy}",
                "followers_url": "https://api.github.com/users/Timtam/followers",
                "following_url": "https://api.github.com/users/Timtam/following{/other_user}",
                "gists_url": "https://api.github.com/users/Timtam/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Timtam",
                "id": 1345878,
                "login": "Timtam",
                "node_id": "MDQ6VXNlcjEzNDU4Nzg=",
                "organizations_url": "https://api.github.com/users/Timtam/orgs",
                "received_events_url": "https://api.github.com/users/Timtam/received_events",
                "repos_url": "https://api.github.com/users/Timtam/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Timtam/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Timtam/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Timtam"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "I was able to find root cause of this issue. I was able to **fix this issue in Coverage code** but I am not 100% sure if it is the right place - see https://github.com/nedbat/coveragepy/issues/972#issuecomment-1079403502 and PR https://github.com/nedbat/coveragepy/pull/1347",
            "created_at": "2022-03-25T20:20:43Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1079404913",
            "id": 1079404913,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc5AVmlx",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1079404913/reactions"
            },
            "updated_at": "2022-03-25T20:20:43Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1079404913",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/827060?v=4",
                "events_url": "https://api.github.com/users/matusvalo/events{/privacy}",
                "followers_url": "https://api.github.com/users/matusvalo/followers",
                "following_url": "https://api.github.com/users/matusvalo/following{/other_user}",
                "gists_url": "https://api.github.com/users/matusvalo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/matusvalo",
                "id": 827060,
                "login": "matusvalo",
                "node_id": "MDQ6VXNlcjgyNzA2MA==",
                "organizations_url": "https://api.github.com/users/matusvalo/orgs",
                "received_events_url": "https://api.github.com/users/matusvalo/received_events",
                "repos_url": "https://api.github.com/users/matusvalo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/matusvalo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/matusvalo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/matusvalo"
            }
        },
        {
            "author_association": "NONE",
            "body": "I've merged https://github.com/nedbat/coveragepy/pull/1347, fyi.",
            "created_at": "2022-08-06T17:39:17Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1207253100",
            "id": 1207253100,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc5H9Ths",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 1,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1207253100/reactions"
            },
            "updated_at": "2022-08-06T17:39:17Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1207253100",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23789?v=4",
                "events_url": "https://api.github.com/users/nedbat/events{/privacy}",
                "followers_url": "https://api.github.com/users/nedbat/followers",
                "following_url": "https://api.github.com/users/nedbat/following{/other_user}",
                "gists_url": "https://api.github.com/users/nedbat/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/nedbat",
                "id": 23789,
                "login": "nedbat",
                "node_id": "MDQ6VXNlcjIzNzg5",
                "organizations_url": "https://api.github.com/users/nedbat/orgs",
                "received_events_url": "https://api.github.com/users/nedbat/received_events",
                "repos_url": "https://api.github.com/users/nedbat/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/nedbat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/nedbat/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/nedbat"
            }
        },
        {
            "author_association": "NONE",
            "body": "Because of https://github.com/nedbat/coveragepy/issues/1538, I might have to rever @matusvalo's fix.  If anyone could look for another solution, I would really appreciate it.",
            "created_at": "2023-01-23T02:35:12Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1399709534",
            "id": 1399709534,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc5Tbd9e",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1399709534/reactions"
            },
            "updated_at": "2023-01-23T02:35:12Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1399709534",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23789?v=4",
                "events_url": "https://api.github.com/users/nedbat/events{/privacy}",
                "followers_url": "https://api.github.com/users/nedbat/followers",
                "following_url": "https://api.github.com/users/nedbat/following{/other_user}",
                "gists_url": "https://api.github.com/users/nedbat/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/nedbat",
                "id": 23789,
                "login": "nedbat",
                "node_id": "MDQ6VXNlcjIzNzg5",
                "organizations_url": "https://api.github.com/users/nedbat/orgs",
                "received_events_url": "https://api.github.com/users/nedbat/received_events",
                "repos_url": "https://api.github.com/users/nedbat/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/nedbat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/nedbat/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/nedbat"
            }
        },
        {
            "author_association": "NONE",
            "body": "If someone could just provide a very very explicit set of instructions for reproducing the problem, that would also be a big help.  Don't assume any knowledge of Cython (I have none).  What steps produce the issue?",
            "created_at": "2023-01-23T02:37:44Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1399711932",
            "id": 1399711932,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc5Tbei8",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1399711932/reactions"
            },
            "updated_at": "2023-01-23T02:37:44Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1399711932",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23789?v=4",
                "events_url": "https://api.github.com/users/nedbat/events{/privacy}",
                "followers_url": "https://api.github.com/users/nedbat/followers",
                "following_url": "https://api.github.com/users/nedbat/following{/other_user}",
                "gists_url": "https://api.github.com/users/nedbat/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/nedbat",
                "id": 23789,
                "login": "nedbat",
                "node_id": "MDQ6VXNlcjIzNzg5",
                "organizations_url": "https://api.github.com/users/nedbat/orgs",
                "received_events_url": "https://api.github.com/users/nedbat/received_events",
                "repos_url": "https://api.github.com/users/nedbat/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/nedbat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/nedbat/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/nedbat"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@nedbat \r\n\r\nCreate the following files:\r\n\r\ncy_mod.pxd\r\n```\r\ncdef class C:\r\n    cdef readonly:\r\n        bint normalize\r\n```\r\n\r\ncy_mod.pyx\r\n```\r\n# cython: linetrace=True\r\n\r\ncdef class C:\r\n    def __init__(self):\r\n        self.normalize = True\r\n```\r\n\r\nmain.py\r\n```\r\nimport cy_mod\r\nprint(cy_mod.C().normalize)\r\n```\r\n\r\n.coveragerc\r\n```\r\n[run]\r\nplugins = Cython.Coverage\r\n```\r\n\r\nNow create a virtualenv like below:\r\n```\r\npython3 -m venv env\r\nsource env/bin/activate\r\npip install cython==3.0.0a11 coverage==6.4.0\r\n```\r\nI've used coverage 6.4.0 as the last release before @matusvalo's fix. However, you may want to use the current working version.\r\n\r\nCompile the Cython module:\r\n```\r\nCFLAGS=\"-DCYTHON_TRACE=1\" cythonize -if cy_mod.pyx\r\n```\r\n\r\nRun coverage on main:\r\n```\r\npython3 -m coverage run main.py\r\n```\r\n\r\nI get `Can't add file tracer data for unmeasured file '<full path>/cy_mod.pxd'`\r\n\r\nThis is all on Linux (may affect what commands you have to run slightly). It also assumes that gcc is installed.",
            "created_at": "2023-01-24T20:23:06Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1402586598",
            "id": 1402586598,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc5TmcXm",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1402586598/reactions"
            },
            "updated_at": "2023-01-24T20:23:06Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1402586598",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "NONE",
            "body": "Thanks, this was very helpful! I confirm that 6.4.0 shows the error, 6.4.3 does not, 7.0.5 does not, and my fix in the works for a performance problem from the 6.4.3 fix also does not show the error.",
            "created_at": "2023-01-25T00:02:47Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1402850158",
            "id": 1402850158,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc5Tnctu",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1402850158/reactions"
            },
            "updated_at": "2023-01-25T00:02:47Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1402850158",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23789?v=4",
                "events_url": "https://api.github.com/users/nedbat/events{/privacy}",
                "followers_url": "https://api.github.com/users/nedbat/followers",
                "following_url": "https://api.github.com/users/nedbat/following{/other_user}",
                "gists_url": "https://api.github.com/users/nedbat/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/nedbat",
                "id": 23789,
                "login": "nedbat",
                "node_id": "MDQ6VXNlcjIzNzg5",
                "organizations_url": "https://api.github.com/users/nedbat/orgs",
                "received_events_url": "https://api.github.com/users/nedbat/received_events",
                "repos_url": "https://api.github.com/users/nedbat/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/nedbat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/nedbat/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/nedbat"
            }
        },
        {
            "author_association": "NONE",
            "body": "Can this issue be closed now? [coverage 7.1.0](https://pypi.org/project/coverage/7.1.0) works without this error.",
            "created_at": "2023-01-25T01:48:48Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1402973888",
            "id": 1402973888,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc5Tn67A",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 1,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1402973888/reactions"
            },
            "updated_at": "2023-01-25T01:48:48Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1402973888",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23789?v=4",
                "events_url": "https://api.github.com/users/nedbat/events{/privacy}",
                "followers_url": "https://api.github.com/users/nedbat/followers",
                "following_url": "https://api.github.com/users/nedbat/following{/other_user}",
                "gists_url": "https://api.github.com/users/nedbat/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/nedbat",
                "id": 23789,
                "login": "nedbat",
                "node_id": "MDQ6VXNlcjIzNzg5",
                "organizations_url": "https://api.github.com/users/nedbat/orgs",
                "received_events_url": "https://api.github.com/users/nedbat/received_events",
                "repos_url": "https://api.github.com/users/nedbat/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/nedbat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/nedbat/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/nedbat"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "> Can this issue be closed now? [coverage 7.1.0](https://pypi.org/project/coverage/7.1.0) works without this error.\r\n\r\n^ @scoder ?",
            "created_at": "2023-01-27T19:26:41Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1406976402",
            "id": 1406976402,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc5T3MGS",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1406976402/reactions"
            },
            "updated_at": "2023-01-27T19:26:41Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1406976402",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
                "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
                "followers_url": "https://api.github.com/users/jakirkham/followers",
                "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
                "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jakirkham",
                "id": 3019665,
                "login": "jakirkham",
                "node_id": "MDQ6VXNlcjMwMTk2NjU=",
                "organizations_url": "https://api.github.com/users/jakirkham/orgs",
                "received_events_url": "https://api.github.com/users/jakirkham/received_events",
                "repos_url": "https://api.github.com/users/jakirkham/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jakirkham"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I think this can be closed. Thanks @nedbat ",
            "created_at": "2023-01-27T22:01:24Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-1407119630",
            "id": 1407119630,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "IC_kwDOABDGAc5T3vEO",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1407119630/reactions"
            },
            "updated_at": "2023-01-27T22:01:24Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1407119630",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        }
    ],
    "comments": 25,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/3515/comments",
    "created_at": "2020-04-14T17:16:31Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2020-04-14T18:07:36Z",
            "event": "labeled",
            "id": 3232295467,
            "label": {
                "color": "444444",
                "name": "defect"
            },
            "node_id": "MDEyOkxhYmVsZWRFdmVudDMyMzIyOTU0Njc=",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/3232295467"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2020-04-14T18:07:36Z",
            "event": "labeled",
            "id": 3232295468,
            "label": {
                "color": "444444",
                "name": "Tools"
            },
            "node_id": "MDEyOkxhYmVsZWRFdmVudDMyMzIyOTU0Njg=",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/3232295468"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/578543?v=4",
                "events_url": "https://api.github.com/users/webknjaz/events{/privacy}",
                "followers_url": "https://api.github.com/users/webknjaz/followers",
                "following_url": "https://api.github.com/users/webknjaz/following{/other_user}",
                "gists_url": "https://api.github.com/users/webknjaz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/webknjaz",
                "id": 578543,
                "login": "webknjaz",
                "node_id": "MDQ6VXNlcjU3ODU0Mw==",
                "organizations_url": "https://api.github.com/users/webknjaz/orgs",
                "received_events_url": "https://api.github.com/users/webknjaz/received_events",
                "repos_url": "https://api.github.com/users/webknjaz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/webknjaz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/webknjaz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/webknjaz"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2020-05-29T15:08:28Z",
            "event": "mentioned",
            "id": 3387620631,
            "node_id": "MDE0Ok1lbnRpb25lZEV2ZW50MzM4NzYyMDYzMQ==",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/3387620631"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/578543?v=4",
                "events_url": "https://api.github.com/users/webknjaz/events{/privacy}",
                "followers_url": "https://api.github.com/users/webknjaz/followers",
                "following_url": "https://api.github.com/users/webknjaz/following{/other_user}",
                "gists_url": "https://api.github.com/users/webknjaz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/webknjaz",
                "id": 578543,
                "login": "webknjaz",
                "node_id": "MDQ6VXNlcjU3ODU0Mw==",
                "organizations_url": "https://api.github.com/users/webknjaz/orgs",
                "received_events_url": "https://api.github.com/users/webknjaz/received_events",
                "repos_url": "https://api.github.com/users/webknjaz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/webknjaz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/webknjaz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/webknjaz"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2020-05-29T15:08:28Z",
            "event": "subscribed",
            "id": 3387620635,
            "node_id": "MDE1OlN1YnNjcmliZWRFdmVudDMzODc2MjA2MzU=",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/3387620635"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/29154557?v=4",
                "events_url": "https://api.github.com/users/Raragyay/events{/privacy}",
                "followers_url": "https://api.github.com/users/Raragyay/followers",
                "following_url": "https://api.github.com/users/Raragyay/following{/other_user}",
                "gists_url": "https://api.github.com/users/Raragyay/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Raragyay",
                "id": 29154557,
                "login": "Raragyay",
                "node_id": "MDQ6VXNlcjI5MTU0NTU3",
                "organizations_url": "https://api.github.com/users/Raragyay/orgs",
                "received_events_url": "https://api.github.com/users/Raragyay/received_events",
                "repos_url": "https://api.github.com/users/Raragyay/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Raragyay/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Raragyay/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Raragyay"
            },
            "commit_id": "f36a154de71e78652e1acf2f3ae5920c023142ad",
            "commit_url": "https://api.github.com/repos/Raragyay/GRGym/commits/f36a154de71e78652e1acf2f3ae5920c023142ad",
            "created_at": "2021-01-07T00:18:23Z",
            "event": "referenced",
            "id": 4177626740,
            "node_id": "MDE1OlJlZmVyZW5jZWRFdmVudDQxNzc2MjY3NDA=",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/4177626740"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/8078968?v=4",
                "events_url": "https://api.github.com/users/jbrockmendel/events{/privacy}",
                "followers_url": "https://api.github.com/users/jbrockmendel/followers",
                "following_url": "https://api.github.com/users/jbrockmendel/following{/other_user}",
                "gists_url": "https://api.github.com/users/jbrockmendel/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jbrockmendel",
                "id": 8078968,
                "login": "jbrockmendel",
                "node_id": "MDQ6VXNlcjgwNzg5Njg=",
                "organizations_url": "https://api.github.com/users/jbrockmendel/orgs",
                "received_events_url": "https://api.github.com/users/jbrockmendel/received_events",
                "repos_url": "https://api.github.com/users/jbrockmendel/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jbrockmendel/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jbrockmendel"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2021-10-06T11:29:00Z",
            "event": "mentioned",
            "id": 5419072604,
            "node_id": "MEE_lADOABDGAc4jvyUUzwAAAAFDAHxc",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/5419072604"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/8078968?v=4",
                "events_url": "https://api.github.com/users/jbrockmendel/events{/privacy}",
                "followers_url": "https://api.github.com/users/jbrockmendel/followers",
                "following_url": "https://api.github.com/users/jbrockmendel/following{/other_user}",
                "gists_url": "https://api.github.com/users/jbrockmendel/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jbrockmendel",
                "id": 8078968,
                "login": "jbrockmendel",
                "node_id": "MDQ6VXNlcjgwNzg5Njg=",
                "organizations_url": "https://api.github.com/users/jbrockmendel/orgs",
                "received_events_url": "https://api.github.com/users/jbrockmendel/received_events",
                "repos_url": "https://api.github.com/users/jbrockmendel/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jbrockmendel/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jbrockmendel"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2021-10-06T11:29:00Z",
            "event": "subscribed",
            "id": 5419072607,
            "node_id": "SE_lADOABDGAc4jvyUUzwAAAAFDAHxf",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/5419072607"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/827060?v=4",
                "events_url": "https://api.github.com/users/matusvalo/events{/privacy}",
                "followers_url": "https://api.github.com/users/matusvalo/followers",
                "following_url": "https://api.github.com/users/matusvalo/following{/other_user}",
                "gists_url": "https://api.github.com/users/matusvalo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/matusvalo",
                "id": 827060,
                "login": "matusvalo",
                "node_id": "MDQ6VXNlcjgyNzA2MA==",
                "organizations_url": "https://api.github.com/users/matusvalo/orgs",
                "received_events_url": "https://api.github.com/users/matusvalo/received_events",
                "repos_url": "https://api.github.com/users/matusvalo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/matusvalo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/matusvalo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/matusvalo"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-01-23T02:35:13Z",
            "event": "mentioned",
            "id": 8330235684,
            "node_id": "MEE_lADOABDGAc4jvyUUzwAAAAHwhU8k",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/8330235684"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/827060?v=4",
                "events_url": "https://api.github.com/users/matusvalo/events{/privacy}",
                "followers_url": "https://api.github.com/users/matusvalo/followers",
                "following_url": "https://api.github.com/users/matusvalo/following{/other_user}",
                "gists_url": "https://api.github.com/users/matusvalo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/matusvalo",
                "id": 827060,
                "login": "matusvalo",
                "node_id": "MDQ6VXNlcjgyNzA2MA==",
                "organizations_url": "https://api.github.com/users/matusvalo/orgs",
                "received_events_url": "https://api.github.com/users/matusvalo/received_events",
                "repos_url": "https://api.github.com/users/matusvalo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/matusvalo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/matusvalo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/matusvalo"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-01-23T02:35:13Z",
            "event": "subscribed",
            "id": 8330235691,
            "node_id": "SE_lADOABDGAc4jvyUUzwAAAAHwhU8r",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/8330235691"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23789?v=4",
                "events_url": "https://api.github.com/users/nedbat/events{/privacy}",
                "followers_url": "https://api.github.com/users/nedbat/followers",
                "following_url": "https://api.github.com/users/nedbat/following{/other_user}",
                "gists_url": "https://api.github.com/users/nedbat/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/nedbat",
                "id": 23789,
                "login": "nedbat",
                "node_id": "MDQ6VXNlcjIzNzg5",
                "organizations_url": "https://api.github.com/users/nedbat/orgs",
                "received_events_url": "https://api.github.com/users/nedbat/received_events",
                "repos_url": "https://api.github.com/users/nedbat/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/nedbat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/nedbat/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/nedbat"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-01-24T20:23:07Z",
            "event": "mentioned",
            "id": 8348062177,
            "node_id": "MEE_lADOABDGAc4jvyUUzwAAAAHxlVHh",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/8348062177"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23789?v=4",
                "events_url": "https://api.github.com/users/nedbat/events{/privacy}",
                "followers_url": "https://api.github.com/users/nedbat/followers",
                "following_url": "https://api.github.com/users/nedbat/following{/other_user}",
                "gists_url": "https://api.github.com/users/nedbat/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/nedbat",
                "id": 23789,
                "login": "nedbat",
                "node_id": "MDQ6VXNlcjIzNzg5",
                "organizations_url": "https://api.github.com/users/nedbat/orgs",
                "received_events_url": "https://api.github.com/users/nedbat/received_events",
                "repos_url": "https://api.github.com/users/nedbat/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/nedbat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/nedbat/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/nedbat"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-01-24T20:23:07Z",
            "event": "subscribed",
            "id": 8348062191,
            "node_id": "SE_lADOABDGAc4jvyUUzwAAAAHxlVHv",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/8348062191"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/827060?v=4",
                "events_url": "https://api.github.com/users/matusvalo/events{/privacy}",
                "followers_url": "https://api.github.com/users/matusvalo/followers",
                "following_url": "https://api.github.com/users/matusvalo/following{/other_user}",
                "gists_url": "https://api.github.com/users/matusvalo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/matusvalo",
                "id": 827060,
                "login": "matusvalo",
                "node_id": "MDQ6VXNlcjgyNzA2MA==",
                "organizations_url": "https://api.github.com/users/matusvalo/orgs",
                "received_events_url": "https://api.github.com/users/matusvalo/received_events",
                "repos_url": "https://api.github.com/users/matusvalo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/matusvalo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/matusvalo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/matusvalo"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-01-24T20:23:07Z",
            "event": "mentioned",
            "id": 8348062220,
            "node_id": "MEE_lADOABDGAc4jvyUUzwAAAAHxlVIM",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/8348062220"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/827060?v=4",
                "events_url": "https://api.github.com/users/matusvalo/events{/privacy}",
                "followers_url": "https://api.github.com/users/matusvalo/followers",
                "following_url": "https://api.github.com/users/matusvalo/following{/other_user}",
                "gists_url": "https://api.github.com/users/matusvalo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/matusvalo",
                "id": 827060,
                "login": "matusvalo",
                "node_id": "MDQ6VXNlcjgyNzA2MA==",
                "organizations_url": "https://api.github.com/users/matusvalo/orgs",
                "received_events_url": "https://api.github.com/users/matusvalo/received_events",
                "repos_url": "https://api.github.com/users/matusvalo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/matusvalo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/matusvalo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/matusvalo"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-01-24T20:23:07Z",
            "event": "subscribed",
            "id": 8348062230,
            "node_id": "SE_lADOABDGAc4jvyUUzwAAAAHxlVIW",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/8348062230"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-01-27T19:26:41Z",
            "event": "mentioned",
            "id": 8376419202,
            "node_id": "MEE_lADOABDGAc4jvyUUzwAAAAHzRgOC",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/8376419202"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-01-27T19:26:41Z",
            "event": "subscribed",
            "id": 8376419216,
            "node_id": "SE_lADOABDGAc4jvyUUzwAAAAHzRgOQ",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/8376419216"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-01-27T22:00:46Z",
            "event": "labeled",
            "id": 8377436274,
            "label": {
                "color": "000000",
                "name": "R: third party"
            },
            "node_id": "LE_lADOABDGAc4jvyUUzwAAAAHzVYhy",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/8377436274"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-01-27T22:01:24Z",
            "event": "closed",
            "id": 8377439504,
            "node_id": "CE_lADOABDGAc4jvyUUzwAAAAHzVZUQ",
            "performed_via_github_app": null,
            "state_reason": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/8377439504"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23789?v=4",
                "events_url": "https://api.github.com/users/nedbat/events{/privacy}",
                "followers_url": "https://api.github.com/users/nedbat/followers",
                "following_url": "https://api.github.com/users/nedbat/following{/other_user}",
                "gists_url": "https://api.github.com/users/nedbat/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/nedbat",
                "id": 23789,
                "login": "nedbat",
                "node_id": "MDQ6VXNlcjIzNzg5",
                "organizations_url": "https://api.github.com/users/nedbat/orgs",
                "received_events_url": "https://api.github.com/users/nedbat/received_events",
                "repos_url": "https://api.github.com/users/nedbat/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/nedbat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/nedbat/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/nedbat"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-01-27T22:01:24Z",
            "event": "mentioned",
            "id": 8377439527,
            "node_id": "MEE_lADOABDGAc4jvyUUzwAAAAHzVZUn",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/8377439527"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23789?v=4",
                "events_url": "https://api.github.com/users/nedbat/events{/privacy}",
                "followers_url": "https://api.github.com/users/nedbat/followers",
                "following_url": "https://api.github.com/users/nedbat/following{/other_user}",
                "gists_url": "https://api.github.com/users/nedbat/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/nedbat",
                "id": 23789,
                "login": "nedbat",
                "node_id": "MDQ6VXNlcjIzNzg5",
                "organizations_url": "https://api.github.com/users/nedbat/orgs",
                "received_events_url": "https://api.github.com/users/nedbat/received_events",
                "repos_url": "https://api.github.com/users/nedbat/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/nedbat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/nedbat/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/nedbat"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-01-27T22:01:24Z",
            "event": "subscribed",
            "id": 8377439536,
            "node_id": "SE_lADOABDGAc4jvyUUzwAAAAHzVZUw",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/8377439536"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/3515/events",
    "html_url": "https://github.com/cython/cython/issues/3515",
    "id": 599729428,
    "labels": [
        {
            "color": "444444",
            "default": false,
            "description": null,
            "id": 425553654,
            "name": "defect",
            "node_id": "MDU6TGFiZWw0MjU1NTM2NTQ=",
            "url": "https://api.github.com/repos/cython/cython/labels/defect"
        },
        {
            "color": "444444",
            "default": false,
            "description": null,
            "id": 425563280,
            "name": "Tools",
            "node_id": "MDU6TGFiZWw0MjU1NjMyODA=",
            "url": "https://api.github.com/repos/cython/cython/labels/Tools"
        },
        {
            "color": "000000",
            "default": false,
            "description": "",
            "id": 1840758668,
            "name": "R: third party",
            "node_id": "MDU6TGFiZWwxODQwNzU4NjY4",
            "url": "https://api.github.com/repos/cython/cython/labels/R:%20third%20party"
        }
    ],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/3515/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU1OTk3Mjk0Mjg=",
    "number": 3515,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/cython/cython/issues/3515/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/3515/timeline",
    "title": "Coverage plugin broken with coverage.py 5.x",
    "updated_at": "2023-01-27T22:01:24Z",
    "url": "https://api.github.com/repos/cython/cython/issues/3515",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/4849151?v=4",
        "events_url": "https://api.github.com/users/jacklovell/events{/privacy}",
        "followers_url": "https://api.github.com/users/jacklovell/followers",
        "following_url": "https://api.github.com/users/jacklovell/following{/other_user}",
        "gists_url": "https://api.github.com/users/jacklovell/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/jacklovell",
        "id": 4849151,
        "login": "jacklovell",
        "node_id": "MDQ6VXNlcjQ4NDkxNTE=",
        "organizations_url": "https://api.github.com/users/jacklovell/orgs",
        "received_events_url": "https://api.github.com/users/jacklovell/received_events",
        "repos_url": "https://api.github.com/users/jacklovell/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/jacklovell/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jacklovell/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/jacklovell"
    }
}