{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "**Describe the bug**\r\nWhen I use pandarallel in cythonized .so file, I get \r\n\r\nTraceback (most recent call last):\r\nFile \"./runtest.py\", line 6, in \r\nparallel_process()\r\nFile \"libtest.py\", line 19, in libtest.parallel_process\r\nFile \"/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py\", line 462, in closure\r\nmap_result,\r\nFile \"/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py\", line 396, in get_workers_result\r\nresults = map_result.get()\r\nFile \"/usr/lib/python3.7/multiprocessing/pool.py\", line 657, in get\r\nraise self._value\r\nSystemError: unknown opcode \r\n\r\n**To Reproduce**\r\nCode to reproduce the behaviour:\r\n```To reproduce:\r\n\r\nCreate library.py and define any function inside which uses parallel_apply on any pandas dataframe\r\nCreate run.py, which imports that function from library and runs. It will run normally.\r\ncythonize -i library.py and try to run run.py - it will fail with SystemError: unknown opcode\r\nWithout pandarallelization, cythonized library works without exception.\r\n```\r\n\r\n**Expected behavior**\r\nCythoinzed function works normally\r\n\r\n**Environment (please complete the following information):**\r\n - OS: Linux\r\n - Python version  3.7.3\r\n - Cython version 0.29.21\r\n - Pandas 1.1.1\r\n - Pandarallel 1.5.1\r\n\r\n**Additional context**\r\nI am not sure its cython fault or pandarallel fault so I created reports in both projects: https://github.com/nalepae/pandarallel/issues/118",
    "closed_at": "2020-11-12T08:28:53Z",
    "comment_data": [
        {
            "author_association": "COLLABORATOR",
            "body": "> Create library.py and define any function inside which uses parallel_apply on any pandas dataframe\r\n> Create run.py, which imports that function from library and runs. It will run normally.\r\n> cythonize -i library.py and try to run run.py - it will fail with SystemError: unknown opcode\r\n> Without pandarallelization, cythonized library works without exception.\r\n\r\nThis is all too vague to be useful. You should assume that people don't know how to use `pandarallel`. Should the function act on the whole dataframe, a row, a column, a cell? (i.e. please provide a small, complete bit of actual code that demonstrates the problem)\r\n\r\nPeople have definitely reported issues with Cython objects not pickling in similar parallelization libraries, but these tend to produce fairly clear error messages. \"unknown opcode\" suggests that memory is being corrupted somewhere.",
            "created_at": "2020-11-11T21:24:50Z",
            "html_url": "https://github.com/cython/cython/issues/3908#issuecomment-725669489",
            "id": 725669489,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3908",
            "node_id": "MDEyOklzc3VlQ29tbWVudDcyNTY2OTQ4OQ==",
            "performed_via_github_app": null,
            "updated_at": "2020-11-11T21:29:42Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/725669489",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "NONE",
            "body": "Sorry for being not clear. I prepared concrete code examples:\r\n\r\n\r\n[cython_pandarallel_fail.tar.gz](https://github.com/cython/cython/files/5528959/cython_pandarallel_fail.tar.gz)\r\n\r\nFirst they can be run by `python test_run1.py` and so on to see that all works with normal input.\r\nThen, if compile lib1.py lib2.py lib3.py with `cythonize -3 -i lib1.py` every of them will fail with\r\n\r\n  \r\n\r\n  `File \"/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py\", line 440, in closure\r\n    kwargs,\r\n\r\n  File \"/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py\", line 303, in get_workers_args\r\n    zip(input_files, output_files, chunk_lengths)\r\n\r\n  File \"/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py\", line 302, in <listcomp>\r\n    for index, (input_file, output_file, chunk_length) in enumerate(\r\n\r\n  File \"/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py\", line 214, in wrapper\r\n    time=time,\r\n\r\n  File \"/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/utils/inliner.py\", line 34, in wrapper\r\n    return function(*args, **kwargs)\r\n\r\n  File \"/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/utils/inliner.py\", line 467, in inline\r\n    func.__closure__,\r\n\r\nTypeError: function() argument 1 must be code, not None`",
            "created_at": "2020-11-12T07:46:24Z",
            "html_url": "https://github.com/cython/cython/issues/3908#issuecomment-725902358",
            "id": 725902358,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3908",
            "node_id": "MDEyOklzc3VlQ29tbWVudDcyNTkwMjM1OA==",
            "performed_via_github_app": null,
            "updated_at": "2020-11-12T07:47:13Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/725902358",
            "user": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/11925386?v=4",
                "events_url": "https://api.github.com/users/LuciusV/events{/privacy}",
                "followers_url": "https://api.github.com/users/LuciusV/followers",
                "following_url": "https://api.github.com/users/LuciusV/following{/other_user}",
                "gists_url": "https://api.github.com/users/LuciusV/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/LuciusV",
                "id": 11925386,
                "login": "LuciusV",
                "node_id": "MDQ6VXNlcjExOTI1Mzg2",
                "organizations_url": "https://api.github.com/users/LuciusV/orgs",
                "received_events_url": "https://api.github.com/users/LuciusV/received_events",
                "repos_url": "https://api.github.com/users/LuciusV/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/LuciusV/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/LuciusV/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/LuciusV"
            }
        },
        {
            "author_association": "COLLABORATOR",
            "body": "So I get\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"test_run1.py\", line 6, in <module>\r\n    result = test_func1()\r\n  File \"lib1.py\", line 10, in lib1.test_func1\r\n    df[\"value\"] = df[\"arg_x\"].parallel_apply(lambda x: np.sin(x))\r\n  File \"<cropped>/pandarallel/pandarallel.py\", line 431, in closure\r\n    workers_args, chunk_lengths, input_files, output_files = get_workers_args(\r\n  File \"<cropped>/pandarallel/pandarallel.py\", line 286, in get_workers_args\r\n    workers_args = [\r\n  File \"<cropped>/pandarallel/pandarallel.py\", line 295, in <listcomp>\r\n    progress_wrapper(\r\n  File \"<cropped>/pandarallel/pandarallel.py\", line 205, in wrapper\r\n    wrapped_func = inline(\r\n  File \"<cropped>/pandarallel/utils/inliner.py\", line 34, in wrapper\r\n    return function(*args, **kwargs)\r\n  File \"<cropped>/pandarallel/utils/inliner.py\", line 462, in inline\r\n    new_func = FunctionType(\r\nTypeError: function() argument 'code' must be code, not None\r\n```\r\n\r\nThis is with Python 3.8, Cython 0.29.21.\r\n\r\nWhat it looks like is that `pandarallel` goes through an [elaborate proceedure to try to introspect to code object of the Python lambda](https://github.com/nalepae/pandarallel/blob/master/pandarallel/utils/inliner.py) and do something clever with it. Since Cython lambdas do not have a code object then this fails.\r\n\r\nIf I changed to using  a function rather than a lambda then it does have a code object (although not one that contains any valid Python code) and I get the \"unknown opcode\" error. In this case `pandarallel`'s introspection proceedure has converted it into nonsense.\r\n\r\nPretty sure this is a bug/limitation in `pandarallel` - it assumes that everything it receives is a Python callable with introspectable Python code objects and makes no effort to do sanity checks if they aren't. Clearly Cython functions are never going to meet this criteria.",
            "created_at": "2020-11-12T08:28:53Z",
            "html_url": "https://github.com/cython/cython/issues/3908#issuecomment-725924528",
            "id": 725924528,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3908",
            "node_id": "MDEyOklzc3VlQ29tbWVudDcyNTkyNDUyOA==",
            "performed_via_github_app": null,
            "updated_at": "2020-11-12T08:28:53Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/725924528",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "NONE",
            "body": "Thank you so much for detailed introspection!",
            "created_at": "2020-11-12T13:33:55Z",
            "html_url": "https://github.com/cython/cython/issues/3908#issuecomment-726080378",
            "id": 726080378,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3908",
            "node_id": "MDEyOklzc3VlQ29tbWVudDcyNjA4MDM3OA==",
            "performed_via_github_app": null,
            "updated_at": "2020-11-12T13:33:55Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/726080378",
            "user": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/11925386?v=4",
                "events_url": "https://api.github.com/users/LuciusV/events{/privacy}",
                "followers_url": "https://api.github.com/users/LuciusV/followers",
                "following_url": "https://api.github.com/users/LuciusV/following{/other_user}",
                "gists_url": "https://api.github.com/users/LuciusV/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/LuciusV",
                "id": 11925386,
                "login": "LuciusV",
                "node_id": "MDQ6VXNlcjExOTI1Mzg2",
                "organizations_url": "https://api.github.com/users/LuciusV/orgs",
                "received_events_url": "https://api.github.com/users/LuciusV/received_events",
                "repos_url": "https://api.github.com/users/LuciusV/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/LuciusV/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/LuciusV/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/LuciusV"
            }
        }
    ],
    "comments": 4,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/3908/comments",
    "created_at": "2020-11-11T04:14:28Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2020-11-11T21:27:12Z",
            "event": "labeled",
            "id": 3985722755,
            "label": {
                "color": "b60205",
                "name": "unclear"
            },
            "node_id": "MDEyOkxhYmVsZWRFdmVudDM5ODU3MjI3NTU=",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/3985722755"
        },
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2020-11-12T08:28:53Z",
            "event": "closed",
            "id": 3987413594,
            "node_id": "MDExOkNsb3NlZEV2ZW50Mzk4NzQxMzU5NA==",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/3987413594"
        },
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2020-11-12T08:29:24Z",
            "event": "unlabeled",
            "id": 3987415690,
            "label": {
                "color": "b60205",
                "name": "unclear"
            },
            "node_id": "MDE0OlVubGFiZWxlZEV2ZW50Mzk4NzQxNTY5MA==",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/3987415690"
        },
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2020-11-12T08:29:24Z",
            "event": "labeled",
            "id": 3987415691,
            "label": {
                "color": "000000",
                "name": "R: third party"
            },
            "node_id": "MDEyOkxhYmVsZWRFdmVudDM5ODc0MTU2OTE=",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/3987415691"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/3908/events",
    "html_url": "https://github.com/cython/cython/issues/3908",
    "id": 740444308,
    "labels": [
        {
            "color": "000000",
            "default": false,
            "description": "",
            "id": 1840758668,
            "name": "R: third party",
            "node_id": "MDU6TGFiZWwxODQwNzU4NjY4",
            "url": "https://api.github.com/repos/cython/cython/labels/R:%20third%20party"
        }
    ],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/3908/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU3NDA0NDQzMDg=",
    "number": 3908,
    "performed_via_github_app": null,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "title": "[BUG] Exception SystemError when using cythonized library with pandarallel",
    "updated_at": "2020-11-12T13:33:56Z",
    "url": "https://api.github.com/repos/cython/cython/issues/3908",
    "user": {
        "avatar_url": "https://avatars3.githubusercontent.com/u/11925386?v=4",
        "events_url": "https://api.github.com/users/LuciusV/events{/privacy}",
        "followers_url": "https://api.github.com/users/LuciusV/followers",
        "following_url": "https://api.github.com/users/LuciusV/following{/other_user}",
        "gists_url": "https://api.github.com/users/LuciusV/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/LuciusV",
        "id": 11925386,
        "login": "LuciusV",
        "node_id": "MDQ6VXNlcjExOTI1Mzg2",
        "organizations_url": "https://api.github.com/users/LuciusV/orgs",
        "received_events_url": "https://api.github.com/users/LuciusV/received_events",
        "repos_url": "https://api.github.com/users/LuciusV/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/LuciusV/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/LuciusV/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/LuciusV"
    }
}