{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "**Describe the bug**\r\nTesting whether a `str` is truthy produces 'deprecated-declarations' warnings when compiling the C code.\r\n\r\n**To Reproduce**\r\nCode to reproduce the behaviour:\r\n```cython\r\ndef bug():\r\n    s = 'hello'\r\n    if s:\r\n        print('non-empty')\r\n```\r\n\r\n**Environment**\r\n - OS: Linux\r\n - Python version: 3.9.0\r\n - Cython version 0.29.21\r\n - C compiler: gcc 9.3.0\r\n\r\nI believe the culprit here is Python 3.9, as I do not see the same behavior for 3.8 (but here I've only tested with Cython `0.29.20`).\r\n\r\n**Additional context**\r\nCompiling the C file generated by the simple code above gives the warnings\r\n\r\n> bug.c: In function ‘__pyx_pf_3bug_bug’:\r\nbug.c:1102:3: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]\r\n 1102 |   __pyx_t_1 = (__Pyx_PyUnicode_IS_TRUE(__pyx_v_s) != 0);\r\n      |   ^~~~~~~~~\r\nIn file included from /home/jmd/concept_installtest/python/include/python3.9/unicodeobject.h:1026,\r\n                 from /home/jmd/concept_installtest/python/include/python3.9/Python.h:97,\r\n                 from bug.c:4:\r\n/home/jmd/concept_installtest/python/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here\r\n  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {\r\n      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~\r\nbug.c:1102:3: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]\r\n 1102 |   __pyx_t_1 = (__Pyx_PyUnicode_IS_TRUE(__pyx_v_s) != 0);\r\n      |   ^~~~~~~~~\r\nIn file included from /home/jmd/concept_installtest/python/include/python3.9/unicodeobject.h:1026,\r\n                 from /home/jmd/concept_installtest/python/include/python3.9/Python.h:97,\r\n                 from bug.c:4:\r\n/home/jmd/concept_installtest/python/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here\r\n  580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(\r\n      |                                             ^~~~~~~~~~~~~~~~~~~\r\nbug.c:1102:3: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]\r\n 1102 |   __pyx_t_1 = (__Pyx_PyUnicode_IS_TRUE(__pyx_v_s) != 0);\r\n      |   ^~~~~~~~~\r\nIn file included from /home/jmd/concept_installtest/python/include/python3.9/unicodeobject.h:1026,\r\n                 from /home/jmd/concept_installtest/python/include/python3.9/Python.h:97,\r\n                 from bug.c:4:\r\n/home/jmd/concept_installtest/python/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here\r\n  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {\r\n      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~\r\n\r\nAll three warnings refer to the same line, where `__Pyx_PyUnicode_IS_TRUE` is used. This is defined by\r\n```C\r\n#if PY_VERSION_HEX > 0x03030000 && defined(PyUnicode_KIND)\r\n  // ...\r\n  #if defined(PyUnicode_IS_READY) && defined(PyUnicode_GET_SIZE)\r\n  #define __Pyx_PyUnicode_IS_TRUE(u)      (0 != (likely(PyUnicode_IS_READY(u)) ? PyUnicode_GET_LENGTH(u) : PyUnicode_GET_SIZE(u)))\r\n  #else\r\n  #define __Pyx_PyUnicode_IS_TRUE(u)      (0 != PyUnicode_GET_LENGTH(u))\r\n  #endif\r\n#else\r\n  // ...\r\n  #define __Pyx_PyUnicode_IS_TRUE(u)      (0 != PyUnicode_GET_SIZE(u))\r\n#endif\r\n```\r\nIf I manually replace ` (0 != (likely(PyUnicode_IS_READY(u)) ? PyUnicode_GET_LENGTH(u) : PyUnicode_GET_SIZE(u)))` with ` (0 != (likely(PyUnicode_IS_READY(u)) ? PyUnicode_GET_LENGTH(u) : PyUnicode_GET_LENGTH(u)))` (or just ` (0 != PyUnicode_GET_LENGTH(u))`), the warnings go away. Oh, and the code works regardless.\r\n\r\nAs far as I can see, the problem is that  `PyUnicode_IS_READY(u)` returns `0` whereas a `1` is expected. Indeed, `PyUnicode_GET_SIZE` has been deprecated in favor of `PyUnicode_GET_LENGTH` since Python 3.3, which makes the sudden appearance of this issue a bit weird. Furthermore, if I check and print the result of `PyUnicode_IS_READY(__pyx_v_s)` (with `__pyx_v_s` corresponding to by `str` `s`), I do indeed get `1`. On further thought, the warnings appear at compile time, so I guess the value of `u` (i.e. `__pyx_v_s`) has nothing to do with it...\r\n\r\nFinally, the bug can be mitigated by switching to using e.g. `if len(s):`.",
    "closed_at": "2025-01-25T09:38:34Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
        "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
        "followers_url": "https://api.github.com/users/da-woods/followers",
        "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
        "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/da-woods",
        "id": 10536947,
        "login": "da-woods",
        "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
        "organizations_url": "https://api.github.com/users/da-woods/orgs",
        "received_events_url": "https://api.github.com/users/da-woods/received_events",
        "repos_url": "https://api.github.com/users/da-woods/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/da-woods",
        "user_view_type": "public"
    },
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "Additional discovery: If I cythonize without `-3`, the warnings disappear.",
            "created_at": "2020-12-01T16:13:02Z",
            "html_url": "https://github.com/cython/cython/issues/3924#issuecomment-736653953",
            "id": 736653953,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3924",
            "node_id": "MDEyOklzc3VlQ29tbWVudDczNjY1Mzk1Mw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/736653953/reactions"
            },
            "updated_at": "2020-12-01T16:13:02Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/736653953",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/9202794?v=4",
                "events_url": "https://api.github.com/users/jmd-dk/events{/privacy}",
                "followers_url": "https://api.github.com/users/jmd-dk/followers",
                "following_url": "https://api.github.com/users/jmd-dk/following{/other_user}",
                "gists_url": "https://api.github.com/users/jmd-dk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jmd-dk",
                "id": 9202794,
                "login": "jmd-dk",
                "node_id": "MDQ6VXNlcjkyMDI3OTQ=",
                "organizations_url": "https://api.github.com/users/jmd-dk/orgs",
                "received_events_url": "https://api.github.com/users/jmd-dk/received_events",
                "repos_url": "https://api.github.com/users/jmd-dk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jmd-dk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jmd-dk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jmd-dk",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "As `PyUnicode_GET_SIZE` is deprecated, would there be any harm in just always going with\r\n```C\r\n#define __Pyx_PyUnicode_IS_TRUE(u)      (0 != PyUnicode_GET_LENGTH(u))\r\n```\r\n? Currently the branch containing `PyUnicode_GET_SIZE` is chosen merely because `PyUnicode_GET_SIZE` is defined, even though `PyUnicode_GET_LENGTH` is also defined. Shouldn't the \"new\" `PyUnicode_GET_LENGTH` get priority, as in\r\n```C\r\n#if defined(PyUnicode_GET_LENGTH)\r\n#define __Pyx_PyUnicode_IS_TRUE(u)      (0 != PyUnicode_GET_LENGTH(u))\r\n#else\r\n#define __Pyx_PyUnicode_IS_TRUE(u)      (0 != PyUnicode_GET_SIZE(u))\r\n#endif\r\n```\r\n?",
            "created_at": "2020-12-01T16:20:50Z",
            "html_url": "https://github.com/cython/cython/issues/3924#issuecomment-736658725",
            "id": 736658725,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3924",
            "node_id": "MDEyOklzc3VlQ29tbWVudDczNjY1ODcyNQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/736658725/reactions"
            },
            "updated_at": "2020-12-01T16:20:50Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/736658725",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/9202794?v=4",
                "events_url": "https://api.github.com/users/jmd-dk/events{/privacy}",
                "followers_url": "https://api.github.com/users/jmd-dk/followers",
                "following_url": "https://api.github.com/users/jmd-dk/following{/other_user}",
                "gists_url": "https://api.github.com/users/jmd-dk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jmd-dk",
                "id": 9202794,
                "login": "jmd-dk",
                "node_id": "MDQ6VXNlcjkyMDI3OTQ=",
                "organizations_url": "https://api.github.com/users/jmd-dk/orgs",
                "received_events_url": "https://api.github.com/users/jmd-dk/received_events",
                "repos_url": "https://api.github.com/users/jmd-dk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jmd-dk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jmd-dk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jmd-dk",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "I'm afraid this issue becomes more pressing, as `PyUnicode_AsUnicode` has been [removed](https://docs.python.org/3/whatsnew/changelog.html#id277) from the C API in Python 3.12.",
            "created_at": "2023-11-15T19:01:18Z",
            "html_url": "https://github.com/cython/cython/issues/3924#issuecomment-1813096026",
            "id": 1813096026,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3924",
            "node_id": "IC_kwDOABDGAc5sEaZa",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1813096026/reactions"
            },
            "updated_at": "2023-11-15T19:01:18Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1813096026",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/102419?v=4",
                "events_url": "https://api.github.com/users/supermihi/events{/privacy}",
                "followers_url": "https://api.github.com/users/supermihi/followers",
                "following_url": "https://api.github.com/users/supermihi/following{/other_user}",
                "gists_url": "https://api.github.com/users/supermihi/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/supermihi",
                "id": 102419,
                "login": "supermihi",
                "node_id": "MDQ6VXNlcjEwMjQxOQ==",
                "organizations_url": "https://api.github.com/users/supermihi/orgs",
                "received_events_url": "https://api.github.com/users/supermihi/received_events",
                "repos_url": "https://api.github.com/users/supermihi/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/supermihi/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/supermihi/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/supermihi",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Cython 3.0 should work just fine.\n",
            "created_at": "2023-11-15T20:46:29Z",
            "html_url": "https://github.com/cython/cython/issues/3924#issuecomment-1813238390",
            "id": 1813238390,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3924",
            "node_id": "IC_kwDOABDGAc5sE9J2",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1813238390/reactions"
            },
            "updated_at": "2023-11-15T20:46:29Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1813238390",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "As should 0.29.x if you're still on it...\r\n\r\n```\r\n#if PY_VERSION_HEX >= 0x030C0000\r\n    #define __Pyx_PyUnicode_IS_TRUE(u)      (0 != PyUnicode_GET_LENGTH(u))\r\n  #else\r\n    #if CYTHON_COMPILING_IN_CPYTHON && PY_VERSION_HEX >= 0x03090000\r\n    #define __Pyx_PyUnicode_IS_TRUE(u)      (0 != (likely(PyUnicode_IS_READY(u)) ? PyUnicode_GET_LENGTH(u) : ((PyCompactUnicodeObject *)(u))->wstr_length))\r\n    #else\r\n    #define __Pyx_PyUnicode_IS_TRUE(u)      (0 != (likely(PyUnicode_IS_READY(u)) ? PyUnicode_GET_LENGTH(u) : PyUnicode_GET_SIZE(u)))\r\n    #endif\r\n  #endif\r\n```\r\n\r\nIt may still trigger the deprecation warning on earlier versions (which i think is why the issue is still open) but it generates the correct code on Python 3.12.",
            "created_at": "2023-11-15T20:48:41Z",
            "html_url": "https://github.com/cython/cython/issues/3924#issuecomment-1813240795",
            "id": 1813240795,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3924",
            "node_id": "IC_kwDOABDGAc5sE9vb",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1813240795/reactions"
            },
            "updated_at": "2023-11-15T20:48:41Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1813240795",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Just for completeness:\r\n\r\nThe one situation that Cython still generate `PyUnicode_AsUnicode` is when you cast to a `Py_UNICODE*`. This isn't a valid thing to do any more after Python 3.12, so if you're using `Py_UNICODE*` in your code you should stop.\r\n\r\nYou probably want to use a `wchar_t*` and `PyUnicode_AsWideCharString` instead - this isn't code Cython can easily generate for you because it involves memory management of raw pointers.\r\n\r\nI've commented with more detail on @supermihi's issue with advice for that particular case. But this is the one situation where Cython still uses generates the deprecated function and it's one that requires the user to replace it - not us.",
            "created_at": "2023-11-15T21:06:06Z",
            "html_url": "https://github.com/cython/cython/issues/3924#issuecomment-1813261257",
            "id": 1813261257,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3924",
            "node_id": "IC_kwDOABDGAc5sFCvJ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1813261257/reactions"
            },
            "updated_at": "2023-11-15T21:06:06Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1813261257",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": ">The one situation that Cython still generate `PyUnicode_AsUnicode` is when you cast to a `Py_UNICODE*`.\r\n\r\nI wonder if it's time already to remove the Py_UNICODE type from Cython 3.1 entirely. It's been deprecated for a while and now removed, and those who still want to use it can resort to Cython 3.0. But I guess we'll end up waiting another while to make less users unhappy with the decision…\r\n\r\nStefan\r\n\r\n",
            "created_at": "2023-11-16T06:30:21Z",
            "html_url": "https://github.com/cython/cython/issues/3924#issuecomment-1813862907",
            "id": 1813862907,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3924",
            "node_id": "IC_kwDOABDGAc5sHVn7",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1813862907/reactions"
            },
            "updated_at": "2023-11-16T06:30:21Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1813862907",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> I wonder if it's time already to remove the Py_UNICODE type from Cython 3.1 entirely. It's been deprecated for a while and now removed, and those who still want to use it can resort to Cython 3.0. But I guess we'll end up waiting another while to make less users unhappy with the decision…\r\n\r\nI think it might at least be worth a Cython-level warning (rather than the C deprecation warning) for the `object -> Py_UNICODE*` coercion explaining that it isn't going to be supported by Cython in 3.12 onwards.",
            "created_at": "2023-11-16T08:05:00Z",
            "html_url": "https://github.com/cython/cython/issues/3924#issuecomment-1813960994",
            "id": 1813960994,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3924",
            "node_id": "IC_kwDOABDGAc5sHtki",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1813960994/reactions"
            },
            "updated_at": "2023-11-16T08:05:00Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1813960994",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "The code block in [Windows and wide character APIs](https://cython.readthedocs.io/en/latest/src/tutorial/strings.html#windows-and-wide-character-apis) no longer compiles. I would welcome a working example for this use case.  ",
            "created_at": "2023-11-16T21:25:11Z",
            "html_url": "https://github.com/cython/cython/issues/3924#issuecomment-1815338477",
            "id": 1815338477,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3924",
            "node_id": "IC_kwDOABDGAc5sM93t",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1815338477/reactions"
            },
            "updated_at": "2023-11-16T21:25:11Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1815338477",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/30911627?v=4",
                "events_url": "https://api.github.com/users/dijkstrah/events{/privacy}",
                "followers_url": "https://api.github.com/users/dijkstrah/followers",
                "following_url": "https://api.github.com/users/dijkstrah/following{/other_user}",
                "gists_url": "https://api.github.com/users/dijkstrah/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/dijkstrah",
                "id": 30911627,
                "login": "dijkstrah",
                "node_id": "MDQ6VXNlcjMwOTExNjI3",
                "organizations_url": "https://api.github.com/users/dijkstrah/orgs",
                "received_events_url": "https://api.github.com/users/dijkstrah/received_events",
                "repos_url": "https://api.github.com/users/dijkstrah/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/dijkstrah/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/dijkstrah/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/dijkstrah",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "@da-woods sorry for incorrectly blaming Cython here. :blush: I fixed my code.",
            "created_at": "2023-11-17T11:44:12Z",
            "html_url": "https://github.com/cython/cython/issues/3924#issuecomment-1816242710",
            "id": 1816242710,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3924",
            "node_id": "IC_kwDOABDGAc5sQaoW",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1816242710/reactions"
            },
            "updated_at": "2023-11-17T11:44:12Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1816242710",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/102419?v=4",
                "events_url": "https://api.github.com/users/supermihi/events{/privacy}",
                "followers_url": "https://api.github.com/users/supermihi/followers",
                "following_url": "https://api.github.com/users/supermihi/following{/other_user}",
                "gists_url": "https://api.github.com/users/supermihi/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/supermihi",
                "id": 102419,
                "login": "supermihi",
                "node_id": "MDQ6VXNlcjEwMjQxOQ==",
                "organizations_url": "https://api.github.com/users/supermihi/orgs",
                "received_events_url": "https://api.github.com/users/supermihi/received_events",
                "repos_url": "https://api.github.com/users/supermihi/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/supermihi/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/supermihi/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/supermihi",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I'm closing this since I think it's long since fixed in supported versions. Probably well before 3.1 but I don't know exactly when.",
            "created_at": "2025-01-25T09:38:34Z",
            "html_url": "https://github.com/cython/cython/issues/3924#issuecomment-2613863945",
            "id": 2613863945,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3924",
            "node_id": "IC_kwDOABDGAc6bzGYJ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/2613863945/reactions"
            },
            "updated_at": "2025-01-25T09:38:34Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/2613863945",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 11,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/3924/comments",
    "created_at": "2020-12-01T16:07:39Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/102419?v=4",
                "events_url": "https://api.github.com/users/supermihi/events{/privacy}",
                "followers_url": "https://api.github.com/users/supermihi/followers",
                "following_url": "https://api.github.com/users/supermihi/following{/other_user}",
                "gists_url": "https://api.github.com/users/supermihi/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/supermihi",
                "id": 102419,
                "login": "supermihi",
                "node_id": "MDQ6VXNlcjEwMjQxOQ==",
                "organizations_url": "https://api.github.com/users/supermihi/orgs",
                "received_events_url": "https://api.github.com/users/supermihi/received_events",
                "repos_url": "https://api.github.com/users/supermihi/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/supermihi/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/supermihi/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/supermihi",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-11-15T21:06:07Z",
            "event": "mentioned",
            "id": 10972265643,
            "node_id": "MEE_lADOABDGAc4s-SZ-zwAAAAKN_3yr",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/10972265643"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/102419?v=4",
                "events_url": "https://api.github.com/users/supermihi/events{/privacy}",
                "followers_url": "https://api.github.com/users/supermihi/followers",
                "following_url": "https://api.github.com/users/supermihi/following{/other_user}",
                "gists_url": "https://api.github.com/users/supermihi/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/supermihi",
                "id": 102419,
                "login": "supermihi",
                "node_id": "MDQ6VXNlcjEwMjQxOQ==",
                "organizations_url": "https://api.github.com/users/supermihi/orgs",
                "received_events_url": "https://api.github.com/users/supermihi/received_events",
                "repos_url": "https://api.github.com/users/supermihi/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/supermihi/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/supermihi/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/supermihi",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-11-15T21:06:07Z",
            "event": "subscribed",
            "id": 10972265648,
            "node_id": "SE_lADOABDGAc4s-SZ-zwAAAAKN_3yw",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/10972265648"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-11-17T11:44:12Z",
            "event": "mentioned",
            "id": 10993237081,
            "node_id": "MEE_lADOABDGAc4s-SZ-zwAAAAKPP3xZ",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/10993237081"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-11-17T11:44:12Z",
            "event": "subscribed",
            "id": 10993237101,
            "node_id": "SE_lADOABDGAc4s-SZ-zwAAAAKPP3xt",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/10993237101"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            },
            "commit_id": "39cebc08fe4eb3d4f8d699a01d35ffe3689c3ec1",
            "commit_url": "https://api.github.com/repos/cython/cython/commits/39cebc08fe4eb3d4f8d699a01d35ffe3689c3ec1",
            "created_at": "2023-11-17T18:34:23Z",
            "event": "referenced",
            "id": 10997785069,
            "node_id": "REFE_lADOABDGAc4s-SZ-zwAAAAKPhOHt",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/10997785069"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2025-01-25T09:38:00Z",
            "event": "milestoned",
            "id": 16067010547,
            "milestone": {
                "title": "3.1"
            },
            "node_id": "MIE_lADOABDGAc4s-SZ-zwAAAAO9qx_z",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/16067010547"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2025-01-25T09:38:34Z",
            "event": "closed",
            "id": 16067011370,
            "node_id": "CE_lADOABDGAc4s-SZ-zwAAAAO9qyMq",
            "performed_via_github_app": null,
            "state_reason": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/16067011370"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/3924/events",
    "html_url": "https://github.com/cython/cython/issues/3924",
    "id": 754525822,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/3924/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": null,
        "closed_issues": 321,
        "created_at": "2019-02-24T14:21:23Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
            "events_url": "https://api.github.com/users/scoder/events{/privacy}",
            "followers_url": "https://api.github.com/users/scoder/followers",
            "following_url": "https://api.github.com/users/scoder/following{/other_user}",
            "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/scoder",
            "id": 491659,
            "login": "scoder",
            "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
            "organizations_url": "https://api.github.com/users/scoder/orgs",
            "received_events_url": "https://api.github.com/users/scoder/received_events",
            "repos_url": "https://api.github.com/users/scoder/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/scoder",
            "user_view_type": "public"
        },
        "description": "* Remove code for Python 2 and Python < 3.8.\r\n* Integrate better with Python 3.\r\n* Improve support for the Limited API.\r\n* Start supporting GIL-free Python 3.13.\r\n* Support the Py3.13 `sys.monitoring` API.\r\n* Support and use `am_send` for coroutines.",
        "due_on": null,
        "html_url": "https://github.com/cython/cython/milestone/65",
        "id": 4082235,
        "labels_url": "https://api.github.com/repos/cython/cython/milestones/65/labels",
        "node_id": "MDk6TWlsZXN0b25lNDA4MjIzNQ==",
        "number": 65,
        "open_issues": 19,
        "state": "open",
        "title": "3.1",
        "updated_at": "2025-01-25T09:47:58Z",
        "url": "https://api.github.com/repos/cython/cython/milestones/65"
    },
    "node_id": "MDU6SXNzdWU3NTQ1MjU4MjI=",
    "number": 3924,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 3,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 3,
        "url": "https://api.github.com/repos/cython/cython/issues/3924/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "state_reason": "completed",
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/3924/timeline",
    "title": "[BUG] Deprecation warnings about _PyUnicode_get_wstr_length and PyUnicode_AsUnicode",
    "updated_at": "2025-01-25T09:38:35Z",
    "url": "https://api.github.com/repos/cython/cython/issues/3924",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/9202794?v=4",
        "events_url": "https://api.github.com/users/jmd-dk/events{/privacy}",
        "followers_url": "https://api.github.com/users/jmd-dk/followers",
        "following_url": "https://api.github.com/users/jmd-dk/following{/other_user}",
        "gists_url": "https://api.github.com/users/jmd-dk/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/jmd-dk",
        "id": 9202794,
        "login": "jmd-dk",
        "node_id": "MDQ6VXNlcjkyMDI3OTQ=",
        "organizations_url": "https://api.github.com/users/jmd-dk/orgs",
        "received_events_url": "https://api.github.com/users/jmd-dk/received_events",
        "repos_url": "https://api.github.com/users/jmd-dk/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/jmd-dk/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jmd-dk/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/jmd-dk",
        "user_view_type": "public"
    }
}