{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Describe the bug\r\n\r\nWhen trying to compile python-llfuse's cython code, it errors out when using it with Python 3.12.0a7 and Cython 0.29.x:\r\n\r\n```\r\nsrc/llfuse.c: In function ‘__Pyx_PyInt_As_time_t’:\r\nsrc/llfuse.c:58504:53: error: ‘PyLongObject {aka struct _longobject}’ has no member named ‘ob_digit’\r\n             const digit* digits = ((PyLongObject*)x)->ob_digit;\r\n                                                     ^~\r\n```\r\n\r\n### Code to reproduce the behaviour:\r\n\r\n```\r\npip install llfuse==1.4.2\r\n```\r\n\r\n\r\n### OS\r\n\r\nUbuntu Linux 18.04\r\n\r\n### Python version\r\n\r\n3.12.0a7\r\n\r\n### Cython version\r\n\r\n0.29.x\r\n\r\n### Additional context\r\n\r\nReported there: https://github.com/python-llfuse/python-llfuse/issues/73",
    "closed_at": "2023-05-07T14:50:31Z",
    "comment_data": [
        {
            "author_association": "NONE",
            "body": "https://github.com/cython/cython/issues/5238\r\n\r\nLooks like this is fixed in cython master branch.\r\n\r\nstate in 0.29.34 unclear: https://github.com/cython/cython/blob/0.29.34/CHANGES.rst\r\n\r\nRelated: https://github.com/cython/cython/issues/5285",
            "created_at": "2023-05-06T19:03:11Z",
            "html_url": "https://github.com/cython/cython/issues/5426#issuecomment-1537203512",
            "id": 1537203512,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5426",
            "node_id": "IC_kwDOABDGAc5bn904",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1537203512/reactions"
            },
            "updated_at": "2023-05-06T19:17:18Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1537203512",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/356103?v=4",
                "events_url": "https://api.github.com/users/ThomasWaldmann/events{/privacy}",
                "followers_url": "https://api.github.com/users/ThomasWaldmann/followers",
                "following_url": "https://api.github.com/users/ThomasWaldmann/following{/other_user}",
                "gists_url": "https://api.github.com/users/ThomasWaldmann/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/ThomasWaldmann",
                "id": 356103,
                "login": "ThomasWaldmann",
                "node_id": "MDQ6VXNlcjM1NjEwMw==",
                "organizations_url": "https://api.github.com/users/ThomasWaldmann/orgs",
                "received_events_url": "https://api.github.com/users/ThomasWaldmann/received_events",
                "repos_url": "https://api.github.com/users/ThomasWaldmann/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/ThomasWaldmann/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ThomasWaldmann/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/ThomasWaldmann"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "As far as I can tell, there is no 0.29 release that contains the fix from commit 1c3a212 (the 0.29.x branch still does not have the fix). That commit is part of the 3.0.0b1 and 3.0.0b2 releases, and is also available on master.",
            "created_at": "2023-05-06T19:27:25Z",
            "html_url": "https://github.com/cython/cython/issues/5426#issuecomment-1537207690",
            "id": 1537207690,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5426",
            "node_id": "IC_kwDOABDGAc5bn-2K",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1537207690/reactions"
            },
            "updated_at": "2023-05-06T19:27:25Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1537207690",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/823911?v=4",
                "events_url": "https://api.github.com/users/mattip/events{/privacy}",
                "followers_url": "https://api.github.com/users/mattip/followers",
                "following_url": "https://api.github.com/users/mattip/following{/other_user}",
                "gists_url": "https://api.github.com/users/mattip/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mattip",
                "id": 823911,
                "login": "mattip",
                "node_id": "MDQ6VXNlcjgyMzkxMQ==",
                "organizations_url": "https://api.github.com/users/mattip/orgs",
                "received_events_url": "https://api.github.com/users/mattip/received_events",
                "repos_url": "https://api.github.com/users/mattip/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mattip/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mattip/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mattip"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "For 0.29.x we just disable the `CYTHON_USE_LONG_INTERNALS` macro. So it should work but potentially with a small performance loss ",
            "created_at": "2023-05-06T19:35:54Z",
            "html_url": "https://github.com/cython/cython/issues/5426#issuecomment-1537209118",
            "id": 1537209118,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5426",
            "node_id": "IC_kwDOABDGAc5bn_Me",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1537209118/reactions"
            },
            "updated_at": "2023-05-06T19:35:54Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1537209118",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "NONE",
            "body": "Is that the fix? This is in 0.29.34:\r\n\r\nhttps://github.com/cython/cython/commit/3397705da036bb2df4a5b8b4bf08dbad7bdb409f\r\n",
            "created_at": "2023-05-06T19:54:05Z",
            "html_url": "https://github.com/cython/cython/issues/5426#issuecomment-1537212047",
            "id": 1537212047,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5426",
            "node_id": "IC_kwDOABDGAc5bn_6P",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1537212047/reactions"
            },
            "updated_at": "2023-05-06T19:54:05Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1537212047",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/356103?v=4",
                "events_url": "https://api.github.com/users/ThomasWaldmann/events{/privacy}",
                "followers_url": "https://api.github.com/users/ThomasWaldmann/followers",
                "following_url": "https://api.github.com/users/ThomasWaldmann/following{/other_user}",
                "gists_url": "https://api.github.com/users/ThomasWaldmann/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/ThomasWaldmann",
                "id": 356103,
                "login": "ThomasWaldmann",
                "node_id": "MDQ6VXNlcjM1NjEwMw==",
                "organizations_url": "https://api.github.com/users/ThomasWaldmann/orgs",
                "received_events_url": "https://api.github.com/users/ThomasWaldmann/received_events",
                "repos_url": "https://api.github.com/users/ThomasWaldmann/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/ThomasWaldmann/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ThomasWaldmann/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/ThomasWaldmann"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> Is that the fix? This is in 0.29.34:\r\n> \r\n> [3397705](https://github.com/cython/cython/commit/3397705da036bb2df4a5b8b4bf08dbad7bdb409f)\r\n\r\nYes that should be it",
            "created_at": "2023-05-07T00:19:09Z",
            "html_url": "https://github.com/cython/cython/issues/5426#issuecomment-1537251064",
            "id": 1537251064,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5426",
            "node_id": "IC_kwDOABDGAc5boJb4",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1537251064/reactions"
            },
            "updated_at": "2023-05-07T00:19:09Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1537251064",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Note that you can always define the C macro to 0 yourself.\n",
            "created_at": "2023-05-07T06:18:32Z",
            "html_url": "https://github.com/cython/cython/issues/5426#issuecomment-1537314568",
            "id": 1537314568,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5426",
            "node_id": "IC_kwDOABDGAc5boY8I",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1537314568/reactions"
            },
            "updated_at": "2023-05-07T06:18:32Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1537314568",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "OK, considering a workaround is in 0.29.34, I guess this could be closed (or kept open a while for better visibility and then closed).",
            "created_at": "2023-05-07T11:49:50Z",
            "html_url": "https://github.com/cython/cython/issues/5426#issuecomment-1537420501",
            "id": 1537420501,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5426",
            "node_id": "IC_kwDOABDGAc5boyzV",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1537420501/reactions"
            },
            "updated_at": "2023-05-07T11:49:50Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1537420501",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/356103?v=4",
                "events_url": "https://api.github.com/users/ThomasWaldmann/events{/privacy}",
                "followers_url": "https://api.github.com/users/ThomasWaldmann/followers",
                "following_url": "https://api.github.com/users/ThomasWaldmann/following{/other_user}",
                "gists_url": "https://api.github.com/users/ThomasWaldmann/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/ThomasWaldmann",
                "id": 356103,
                "login": "ThomasWaldmann",
                "node_id": "MDQ6VXNlcjM1NjEwMw==",
                "organizations_url": "https://api.github.com/users/ThomasWaldmann/orgs",
                "received_events_url": "https://api.github.com/users/ThomasWaldmann/received_events",
                "repos_url": "https://api.github.com/users/ThomasWaldmann/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/ThomasWaldmann/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ThomasWaldmann/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/ThomasWaldmann"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I think it's fixed on both branches to the extent we plan to, so I'll close it",
            "created_at": "2023-05-07T14:50:31Z",
            "html_url": "https://github.com/cython/cython/issues/5426#issuecomment-1537459825",
            "id": 1537459825,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5426",
            "node_id": "IC_kwDOABDGAc5bo8Zx",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1537459825/reactions"
            },
            "updated_at": "2023-05-07T14:50:31Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1537459825",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        }
    ],
    "comments": 8,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/5426/comments",
    "created_at": "2023-05-06T18:52:53Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-05-07T14:50:31Z",
            "event": "closed",
            "id": 9184432185,
            "node_id": "CE_lADOABDGAc5lQKw0zwAAAAIjb1A5",
            "performed_via_github_app": null,
            "state_reason": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9184432185"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/5426/events",
    "html_url": "https://github.com/cython/cython/issues/5426",
    "id": 1698737204,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/5426/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOABDGAc5lQKw0",
    "number": 5426,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/cython/cython/issues/5426/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/5426/timeline",
    "title": "[BUG] ob_digit is unknown in Python 3.12a",
    "updated_at": "2023-05-07T14:50:31Z",
    "url": "https://api.github.com/repos/cython/cython/issues/5426",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/356103?v=4",
        "events_url": "https://api.github.com/users/ThomasWaldmann/events{/privacy}",
        "followers_url": "https://api.github.com/users/ThomasWaldmann/followers",
        "following_url": "https://api.github.com/users/ThomasWaldmann/following{/other_user}",
        "gists_url": "https://api.github.com/users/ThomasWaldmann/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/ThomasWaldmann",
        "id": 356103,
        "login": "ThomasWaldmann",
        "node_id": "MDQ6VXNlcjM1NjEwMw==",
        "organizations_url": "https://api.github.com/users/ThomasWaldmann/orgs",
        "received_events_url": "https://api.github.com/users/ThomasWaldmann/received_events",
        "repos_url": "https://api.github.com/users/ThomasWaldmann/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/ThomasWaldmann/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ThomasWaldmann/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/ThomasWaldmann"
    }
}