{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "### Describe the bug\r\n\r\nWhen compiling with `linetrace=True`, compilation fails with:\r\n\r\n```\r\nerror: ‘_PyCFrame’ has no member named ‘use_tracing’\r\n```\r\n\r\n<details>\r\n<summary>full output</summary>\r\n\r\n```\r\n/root/.pyxbld/temp.linux-aarch64-cpython-312/io/ctest.c: In function ‘__pyx_f_5ctest_twice’:\r\n/root/.pyxbld/temp.linux-aarch64-cpython-312/io/ctest.c:1537:32: error: ‘_PyCFrame’ has no member named ‘use_tracing’\r\n 1537 |      (unlikely((tstate)->cframe->use_tracing) &&\\\r\n      |                                ^~\r\n/root/.pyxbld/temp.linux-aarch64-cpython-312/io/ctest.c:1330:43: note: in definition of macro ‘unlikely’\r\n 1330 |   #define unlikely(x) __builtin_expect(!!(x), 0)\r\n      |                                           ^\r\n/root/.pyxbld/temp.linux-aarch64-cpython-312/io/ctest.c:1576:15: note: in expansion of macro ‘__Pyx_IsTracing’\r\n 1576 |           if (__Pyx_IsTracing(tstate, 1, 1)) {\\\r\n      |               ^~~~~~~~~~~~~~~\r\n/root/.pyxbld/temp.linux-aarch64-cpython-312/io/ctest.c:2250:3: note: in expansion of macro ‘__Pyx_TraceCall’\r\n 2250 |   __Pyx_TraceCall(\"twice\", __pyx_f[0], 3, 0, __PYX_ERR(0, 3, __pyx_L1_error));\r\n      |   ^~~~~~~~~~~~~~~\r\n```\r\n\r\n</details>\r\n\r\n\r\n### Code to reproduce the behaviour:\r\n\r\n```cython\r\n#cython: linetrace=True\r\n\r\ncpdef int twice(int x):\r\n    return 2 * x\r\n```\r\n\r\n\r\n### Expected behaviour\r\n\r\nNo error\r\n\r\n### OS\r\n\r\nLinux (arm64, docker image python:3.12.0b1)\r\n\r\n### Python version\r\n\r\n3.12.0b1\r\n\r\n### Cython version\r\n\r\n3.0.0b3\r\n\r\n### Additional context\r\n\r\nMinimal test case tested via pyximport in arm64 `python:3.12.0b1` docker image (`sha256:64a039039087f8a7fde61b973dc3137ab9494979948b98435421a125f386a967`), originally found [on pyzmq](https://github.com/zeromq/pyzmq/actions/runs/5088487428/jobs/9144951722#step:16:217)",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/5450/comments",
    "created_at": "2023-05-26T08:24:54Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
                "events_url": "https://api.github.com/users/minrk/events{/privacy}",
                "followers_url": "https://api.github.com/users/minrk/followers",
                "following_url": "https://api.github.com/users/minrk/following{/other_user}",
                "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/minrk",
                "id": 151929,
                "login": "minrk",
                "node_id": "MDQ6VXNlcjE1MTkyOQ==",
                "organizations_url": "https://api.github.com/users/minrk/orgs",
                "received_events_url": "https://api.github.com/users/minrk/received_events",
                "repos_url": "https://api.github.com/users/minrk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/minrk"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-05-26T08:30:02Z",
            "event": "renamed",
            "id": 9347985498,
            "node_id": "RTE_lADOABDGAc5m8i-ZzwAAAAItLvBa",
            "performed_via_github_app": null,
            "rename": {
                "from": "[BUG] linetrace fails with 3.12 + 3.0.0b3",
                "to": "[BUG] compilation with linetrace fails with 3.12 + 3.0.0b3"
            },
            "url": "https://api.github.com/repos/cython/cython/issues/events/9347985498"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/5450/events",
    "html_url": "https://github.com/cython/cython/issues/5450",
    "id": 1727147929,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/5450/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOABDGAc5m8i-Z",
    "number": 5450,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/cython/cython/issues/5450/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/5450/timeline",
    "title": "[BUG] compilation with linetrace fails with 3.12 + 3.0.0b3",
    "updated_at": "2023-05-26T08:30:02Z",
    "url": "https://api.github.com/repos/cython/cython/issues/5450",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
        "events_url": "https://api.github.com/users/minrk/events{/privacy}",
        "followers_url": "https://api.github.com/users/minrk/followers",
        "following_url": "https://api.github.com/users/minrk/following{/other_user}",
        "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/minrk",
        "id": 151929,
        "login": "minrk",
        "node_id": "MDQ6VXNlcjE1MTkyOQ==",
        "organizations_url": "https://api.github.com/users/minrk/orgs",
        "received_events_url": "https://api.github.com/users/minrk/received_events",
        "repos_url": "https://api.github.com/users/minrk/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/minrk"
    }
}