{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "### Describe the bug\r\n\r\nPEP-669 (https://peps.python.org/pep-0669/) and its implementation in https://github.com/python/cpython/pull/103083 change the internals of CPython's tracing in Py3.12. We need to adapt. Currently, profiling fails in Py3.12.\r\n\r\nCompilation was already fixed in https://github.com/cython/cython/commit/03c498d3142ccee2da258c540e96f12c863159fc (#5450), but that doesn't make the feature work again.\r\n\r\nTest failure:\r\n\r\n<details>\r\n\r\n```\r\n======================================================================\r\nFAIL: pstats_profile_test ()\r\nDoctest: pstats_profile_test\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 2228, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for pstats_profile_test\r\n  File \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 1, in pstats_profile_test\r\n\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 8, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_def']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[5]>\", line 1, in <module>\r\n        short_stats['f_def']\r\n        ~~~~~~~~~~~^^^^^^^^^\r\n    KeyError: 'f_def'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 10, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_cdef']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[6]>\", line 1, in <module>\r\n        short_stats['f_cdef']\r\n        ~~~~~~~~~~~^^^^^^^^^^\r\n    KeyError: 'f_cdef'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 12, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_cpdef']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[7]>\", line 1, in <module>\r\n        short_stats['f_cpdef']\r\n        ~~~~~~~~~~~^^^^^^^^^^^\r\n    KeyError: 'f_cpdef'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 14, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_inline']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[8]>\", line 1, in <module>\r\n        short_stats['f_inline']\r\n        ~~~~~~~~~~~^^^^^^^^^^^^\r\n    KeyError: 'f_inline'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 16, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_inline_prof']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[9]>\", line 1, in <module>\r\n        short_stats['f_inline_prof']\r\n        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^\r\n    KeyError: 'f_inline_prof'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 22, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_raise']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[11]>\", line 1, in <module>\r\n        short_stats['f_raise']\r\n        ~~~~~~~~~~~^^^^^^^^^^^\r\n    KeyError: 'f_raise'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 25, in pstats_profile_test\r\nFailed example:\r\n    short_stats['withgil_prof']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[12]>\", line 1, in <module>\r\n        short_stats['withgil_prof']\r\n        ~~~~~~~~~~~^^^^^^^^^^^^^^^^\r\n    KeyError: 'withgil_prof'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 41, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_raise']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[16]>\", line 1, in <module>\r\n        short_stats['f_raise']\r\n        ~~~~~~~~~~~^^^^^^^^^^^\r\n    KeyError: 'f_raise'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 44, in pstats_profile_test\r\nFailed example:\r\n    short_stats['m_def']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[17]>\", line 1, in <module>\r\n        short_stats['m_def']\r\n        ~~~~~~~~~~~^^^^^^^^^\r\n    KeyError: 'm_def'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 46, in pstats_profile_test\r\nFailed example:\r\n    short_stats['m_cdef']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[18]>\", line 1, in <module>\r\n        short_stats['m_cdef']\r\n        ~~~~~~~~~~~^^^^^^^^^^\r\n    KeyError: 'm_cdef'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 48, in pstats_profile_test\r\nFailed example:\r\n    short_stats['m_cpdef'] - (200 if CPDEF_METHODS_COUNT_TWICE else 0)  # FIXME!\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[19]>\", line 1, in <module>\r\n        short_stats['m_cpdef'] - (200 if CPDEF_METHODS_COUNT_TWICE else 0)  # FIXME!\r\n        ~~~~~~~~~~~^^^^^^^^^^^\r\n    KeyError: 'm_cpdef'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 56, in pstats_profile_test\r\nFailed example:\r\n    sorted(callees(s, 'test_profile'))  #doctest: +NORMALIZE_WHITESPACE\r\nExpected:\r\n    ['f_cdef', 'f_cpdef', 'f_def',\r\n     'f_inline', 'f_inline_prof',\r\n     'f_raise',\r\n     'm_cdef', 'm_cpdef', 'm_def',\r\n     'withgil_prof']\r\nGot:\r\n    []\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 66, in pstats_profile_test\r\nFailed example:\r\n    short_stats['generator']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[25]>\", line 1, in <module>\r\n        short_stats['generator']\r\n        ~~~~~~~~~~~^^^^^^^^^^^^^\r\n    KeyError: 'generator'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 69, in pstats_profile_test\r\nFailed example:\r\n    short_stats['generator_exception']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[26]>\", line 1, in <module>\r\n        short_stats['generator_exception']\r\n        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\r\n    KeyError: 'generator_exception'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 72, in pstats_profile_test\r\nFailed example:\r\n    short_stats['genexpr']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[27]>\", line 1, in <module>\r\n        short_stats['genexpr']\r\n        ~~~~~~~~~~~^^^^^^^^^^^\r\n    KeyError: 'genexpr'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 75, in pstats_profile_test\r\nFailed example:\r\n    sorted(callees(s, 'test_generators'))\r\nExpected:\r\n    ['call_generator', 'call_generator_exception', 'generator_expr']\r\nGot:\r\n    []\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 78, in pstats_profile_test\r\nFailed example:\r\n    list(callees(s, 'call_generator'))\r\nExpected:\r\n    ['generator']\r\nGot:\r\n    []\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 87, in pstats_profile_test\r\nFailed example:\r\n    list(callees(s, 'generator_expr'))\r\nExpected:\r\n    ['genexpr']\r\nGot:\r\n    []\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 107, in pstats_profile_test\r\nFailed example:\r\n    python_stats_dict['python_generator'] == cython_stats_dict['generator']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[42]>\", line 1, in <module>\r\n        python_stats_dict['python_generator'] == cython_stats_dict['generator']\r\n                                                 ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\r\n    KeyError: 'generator'\r\n```\r\n</details>\r\n\r\n### Code to reproduce the behaviour:\r\n\r\n_No response_\r\n\r\n### Expected behaviour\r\n\r\n_No response_\r\n\r\n### OS\r\n\r\n_No response_\r\n\r\n### Python version\r\n\r\n3.12.0b1\r\n\r\n### Cython version\r\n\r\ncurrent master (3.0.0b3)\r\n\r\n### Additional context\r\n\r\n_No response_",
    "closed_at": "2025-02-11T09:11:07Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
        "events_url": "https://api.github.com/users/scoder/events{/privacy}",
        "followers_url": "https://api.github.com/users/scoder/followers",
        "following_url": "https://api.github.com/users/scoder/following{/other_user}",
        "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/scoder",
        "id": 491659,
        "login": "scoder",
        "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
        "organizations_url": "https://api.github.com/users/scoder/orgs",
        "received_events_url": "https://api.github.com/users/scoder/received_events",
        "repos_url": "https://api.github.com/users/scoder/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/scoder",
        "user_view_type": "public"
    },
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "Detail tags and triple backticks need to be separated by a newline for the rendering to not be broken.",
            "created_at": "2023-06-06T09:02:47Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-1578245707",
            "id": 1578245707,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc5eEh5L",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1578245707/reactions"
            },
            "updated_at": "2023-11-12T08:28:03Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1578245707",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/33685575?v=4",
                "events_url": "https://api.github.com/users/h-vetinari/events{/privacy}",
                "followers_url": "https://api.github.com/users/h-vetinari/followers",
                "following_url": "https://api.github.com/users/h-vetinari/following{/other_user}",
                "gists_url": "https://api.github.com/users/h-vetinari/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/h-vetinari",
                "id": 33685575,
                "login": "h-vetinari",
                "node_id": "MDQ6VXNlcjMzNjg1NTc1",
                "organizations_url": "https://api.github.com/users/h-vetinari/orgs",
                "received_events_url": "https://api.github.com/users/h-vetinari/received_events",
                "repos_url": "https://api.github.com/users/h-vetinari/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/h-vetinari/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/h-vetinari/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/h-vetinari",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "Is there a chance that this could be in before the final release of 3.12? Also will this functionality be restored for 0.2.x version?",
            "created_at": "2023-08-29T04:27:51Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-1696746901",
            "id": 1696746901,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc5lIk2V",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1696746901/reactions"
            },
            "updated_at": "2023-08-29T04:27:51Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1696746901",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/44142765?v=4",
                "events_url": "https://api.github.com/users/zoj613/events{/privacy}",
                "followers_url": "https://api.github.com/users/zoj613/followers",
                "following_url": "https://api.github.com/users/zoj613/following{/other_user}",
                "gists_url": "https://api.github.com/users/zoj613/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zoj613",
                "id": 44142765,
                "login": "zoj613",
                "node_id": "MDQ6VXNlcjQ0MTQyNzY1",
                "organizations_url": "https://api.github.com/users/zoj613/orgs",
                "received_events_url": "https://api.github.com/users/zoj613/received_events",
                "repos_url": "https://api.github.com/users/zoj613/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zoj613/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zoj613/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zoj613",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> Is there a chance that this could be in before the final release of 3.12?\r\n\r\nIf someone repairs it in time, then yes. Investigations and/or PR is welcome.\r\n\r\nBasically, someone has to figure out how tracing can be done in Python 3.12 now. The CPython project broke their C-API, so they probably have a (documented?) idea somewhere how to migrate.\r\n\r\n\r\n> will this functionality be restored for 0.2.x version?\r\n\r\nThis is out of scope for future 0.29.x releases. We could add an explicit C warning there, though, when users try to use tracing in Py3.12. You can use Python 3.11 for profiling/tracing with 0.29.x.",
            "created_at": "2023-08-29T07:17:13Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-1696899337",
            "id": 1696899337,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc5lJKEJ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1696899337/reactions"
            },
            "updated_at": "2023-08-29T07:17:13Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1696899337",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Quote from @da-woods in https://github.com/cython/cython/issues/5813\r\n\r\nProfiling on Py3.12+ is currently broken. Here are my notes from looking into it:\r\n\r\n* `PyEval_SetProfile` is now \"legacy\". It still works, and I believe Cython would still interact correctly with it if it were used. However, the standard library profile modules don't use it.\r\n* The current preferred way is via [`sys.monitoring`](https://docs.python.org/3/library/sys.monitoring.html#module-sys.monitoring), and this is what profile/cProfile do.\r\n* `PyEval_SetProfile` sets up functions using the new \"monitoring\" approach, however, things that use the new \"monitoring\" approach don't trigger the old `PyEval_SetProfile` way. Therefore, if we want to interact with all profiling tools we really need to use the new \"monitoring\" approach.\r\n* I think the right thing to do would be to call [`_Py_call_instrumentation`](https://github.com/python/cpython/blob/fa84e5fe0a3bd8e77c33b20867d71ac6bee270f9/Python/instrumentation.c#L1035C1) (or something similar). Unfortunately these are internal symbols so fail at the link stage (even if include the internal headers).\r\n* There doesn't seem to be an easy way to check if profiling is enabled. However, `_Py_call_instrumentation` looks to return very quickly if it isn't, so I think that's OK.\r\n* The linking errors are largely where I got stuck - there doesn't seem to be any accessible way to trigger a profiling event manually.",
            "created_at": "2023-11-12T08:28:18Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-1807054938",
            "id": 1807054938,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc5rtXha",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1807054938/reactions"
            },
            "updated_at": "2023-11-12T08:28:18Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1807054938",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I created https://github.com/python/cpython/issues/111997 for designing a new signalling C-API in CPython.",
            "created_at": "2023-11-12T08:29:38Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-1807055254",
            "id": 1807055254,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc5rtXmW",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1807055254/reactions"
            },
            "updated_at": "2023-11-12T08:29:38Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1807055254",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "My proposal for now is just to remove the test from Python 3.12: https://github.com/cython/cython/pull/5815.\r\n\r\nI suspect if people really needed to profile Cython+Python 3.12 they could cprofile/profile from Python 3.11 and it'd work (because they'd use the \"legacy\" method). But I don't think that's something we should provide ourself.",
            "created_at": "2023-11-12T13:38:20Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-1807131600",
            "id": 1807131600,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc5rtqPQ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1807131600/reactions"
            },
            "updated_at": "2023-11-12T13:38:20Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1807131600",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Some more information that I was able to collect:\r\n\r\nWe probably need to build a [line table](https://github.com/python/cpython/blob/main/Objects/locations.md). CPython [has C code for this](https://github.com/python/cpython/blob/d67f947c72af8a215db2fd285e5de9b1e671fde1/Python/assemble.c#L190-L444) in `assemble.c`, but we need a Python implementation that runs at translation time _and_ an idea for a reasonable mapping of Cython's code positions to reportable event positions.\r\n\r\nThe code enum (bits 3-6) is defined here:\r\nhttps://github.com/python/cpython/blob/d67f947c72af8a215db2fd285e5de9b1e671fde1/Include/cpython/code.h#L378-L389\r\n",
            "created_at": "2023-11-21T11:27:47Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-1820737158",
            "id": 1820737158,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc5shj6G",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1820737158/reactions"
            },
            "updated_at": "2023-11-21T13:04:56Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1820737158",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "> This is out of scope for future 0.29.x releases. \r\n\r\nI noticed that 0.29.x releases produce a cpp code that doesn't compile, when `cython: profile=True` directive is set. However,  on Cython 3.x, the code compiles. Given that:\r\n\r\n> Profiling on Py3.12+ is currently broken\r\n\r\n what is the current behavior on Cython 3.x when  `cython: profile=True` is present? Is it silently ignored? \r\n \r\n Would it make sense to adjust Cython 0.29  to ignore this directive for Python 3.12 , or 0.29.x family is no longer developed and the workaround  to ignore the profiling directive  won't be back-ported? Thanks.\r\n",
            "created_at": "2024-04-02T01:36:30Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-2030917844",
            "id": 2030917844,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc55DVjU",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/2030917844/reactions"
            },
            "updated_at": "2024-04-02T01:36:54Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/2030917844",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/9408864?v=4",
                "events_url": "https://api.github.com/users/tvalentyn/events{/privacy}",
                "followers_url": "https://api.github.com/users/tvalentyn/followers",
                "following_url": "https://api.github.com/users/tvalentyn/following{/other_user}",
                "gists_url": "https://api.github.com/users/tvalentyn/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/tvalentyn",
                "id": 9408864,
                "login": "tvalentyn",
                "node_id": "MDQ6VXNlcjk0MDg4NjQ=",
                "organizations_url": "https://api.github.com/users/tvalentyn/orgs",
                "received_events_url": "https://api.github.com/users/tvalentyn/received_events",
                "repos_url": "https://api.github.com/users/tvalentyn/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/tvalentyn/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tvalentyn/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/tvalentyn",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> what is the current behavior on Cython 3.x when `cython: profile=True` is present? Is it silently ignored?\r\n\r\nIf I remember right, it doesn't do anything. Not deliberately but because it just invokes the old profiling mechanism, but Python is only listening for the new one.\r\n\r\n> Would it make sense to adjust Cython 0.29 to ignore this directive for Python 3.12 , or 0.29.x family is no longer developed and the workaround to ignore the profiling directive won't be back-ported?\r\n\r\n0.29.x is \"important bug fixes only\". My feeling is that this doesn't meet the criteria, but if it were a simple change then we'd consider it.",
            "created_at": "2024-04-02T06:08:22Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-2031146880",
            "id": 2031146880,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc55ENeA",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/2031146880/reactions"
            },
            "updated_at": "2024-04-02T06:08:22Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/2031146880",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "> if it were a simple change then we'd consider it.\r\n\r\nI came up with: https://github.com/cython/cython/pull/6125. We could include it if we expect usage of Cython 0.29 on 3.12. \r\nDoes Cython have  a plan to cap an upper bound of allowed  Python minor version for the 0.29 version family?",
            "created_at": "2024-04-02T22:45:05Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-2033227582",
            "id": 2033227582,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc55MJc-",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/2033227582/reactions"
            },
            "updated_at": "2024-04-02T22:45:50Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/2033227582",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/9408864?v=4",
                "events_url": "https://api.github.com/users/tvalentyn/events{/privacy}",
                "followers_url": "https://api.github.com/users/tvalentyn/followers",
                "following_url": "https://api.github.com/users/tvalentyn/following{/other_user}",
                "gists_url": "https://api.github.com/users/tvalentyn/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/tvalentyn",
                "id": 9408864,
                "login": "tvalentyn",
                "node_id": "MDQ6VXNlcjk0MDg4NjQ=",
                "organizations_url": "https://api.github.com/users/tvalentyn/orgs",
                "received_events_url": "https://api.github.com/users/tvalentyn/received_events",
                "repos_url": "https://api.github.com/users/tvalentyn/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/tvalentyn/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tvalentyn/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/tvalentyn",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I've started on an implementation for Py3.13, based on the newly designed monitoring C-API. I'll see how that goes.\r\nhttps://github.com/python/cpython/issues/111997",
            "created_at": "2024-04-15T10:08:49Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-2056451053",
            "id": 2056451053,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc56kvPt",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 1,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/2056451053/reactions"
            },
            "updated_at": "2024-04-15T10:08:49Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/2056451053",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "@scoder, I see that the issue you linked in your [most recent comment above](https://github.com/cython/cython/issues/5470#issuecomment-2056451053) is now closed. Do we know what work remains to fix this? I'd love to be able to profile my .pyx functions with cProfile in Python 3.13, if possible.",
            "created_at": "2024-12-02T22:03:01Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-2513031675",
            "id": 2513031675,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc6VydH7",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/2513031675/reactions"
            },
            "updated_at": "2024-12-02T22:03:01Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/2513031675",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/106544999?v=4",
                "events_url": "https://api.github.com/users/ogiarch/events{/privacy}",
                "followers_url": "https://api.github.com/users/ogiarch/followers",
                "following_url": "https://api.github.com/users/ogiarch/following{/other_user}",
                "gists_url": "https://api.github.com/users/ogiarch/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/ogiarch",
                "id": 106544999,
                "login": "ogiarch",
                "node_id": "U_kgDOBlm_Zw",
                "organizations_url": "https://api.github.com/users/ogiarch/orgs",
                "received_events_url": "https://api.github.com/users/ogiarch/received_events",
                "repos_url": "https://api.github.com/users/ogiarch/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/ogiarch/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ogiarch/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/ogiarch",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "This is not going to be changed in Cython 3.0.x any more. 3.1 has a new implementation, so I'll close this ticket.",
            "created_at": "2025-02-11T09:11:07Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-2650209216",
            "id": 2650209216,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc6d9vvA",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/2650209216/reactions"
            },
            "updated_at": "2025-02-11T09:11:07Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/2650209216",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 13,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/5470/comments",
    "created_at": "2023-06-06T08:40:46Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-06-06T08:40:46Z",
            "event": "labeled",
            "id": 9443295515,
            "label": {
                "color": "444444",
                "name": "defect"
            },
            "node_id": "LE_lADOABDGAc5n6c3nzwAAAAIy3UEb",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9443295515"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-06-06T08:40:46Z",
            "event": "labeled",
            "id": 9443295519,
            "label": {
                "color": "444444",
                "name": "Python Semantics"
            },
            "node_id": "LE_lADOABDGAc5n6c3nzwAAAAIy3UEf",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9443295519"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-06-06T08:40:46Z",
            "event": "milestoned",
            "id": 9443295538,
            "milestone": {
                "title": "3.0"
            },
            "node_id": "MIE_lADOABDGAc5n6c3nzwAAAAIy3UEy",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9443295538"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-07-23T13:00:24Z",
            "event": "demilestoned",
            "id": 9892738208,
            "milestone": {
                "title": "3.0"
            },
            "node_id": "DEME_lADOABDGAc5n6c3nzwAAAAJNpzSg",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9892738208"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-07-23T13:00:24Z",
            "event": "milestoned",
            "id": 9892738211,
            "milestone": {
                "title": "3.0.x"
            },
            "node_id": "MIE_lADOABDGAc5n6c3nzwAAAAJNpzSj",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9892738211"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-11-12T08:28:18Z",
            "event": "mentioned",
            "id": 10934032618,
            "node_id": "MEE_lADOABDGAc5n6c3nzwAAAAKLuBjq",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/10934032618"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-11-12T08:28:18Z",
            "event": "subscribed",
            "id": 10934032620,
            "node_id": "SE_lADOABDGAc5n6c3nzwAAAAKLuBjs",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/10934032620"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/129501?v=4",
                "events_url": "https://api.github.com/users/ionelmc/events{/privacy}",
                "followers_url": "https://api.github.com/users/ionelmc/followers",
                "following_url": "https://api.github.com/users/ionelmc/following{/other_user}",
                "gists_url": "https://api.github.com/users/ionelmc/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/ionelmc",
                "id": 129501,
                "login": "ionelmc",
                "node_id": "MDQ6VXNlcjEyOTUwMQ==",
                "organizations_url": "https://api.github.com/users/ionelmc/orgs",
                "received_events_url": "https://api.github.com/users/ionelmc/received_events",
                "repos_url": "https://api.github.com/users/ionelmc/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/ionelmc/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ionelmc/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/ionelmc",
                "user_view_type": "public"
            },
            "commit_id": "3fbc676721518884a8194ca059656ffb8dd802cb",
            "commit_url": "https://api.github.com/repos/ionelmc/python-hunter/commits/3fbc676721518884a8194ca059656ffb8dd802cb",
            "created_at": "2024-05-01T20:41:22Z",
            "event": "referenced",
            "id": 12674702220,
            "node_id": "REFE_lADOABDGAc5n6c3nzwAAAALzeJuM",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/12674702220"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/5265893?v=4",
                "events_url": "https://api.github.com/users/vfazio/events{/privacy}",
                "followers_url": "https://api.github.com/users/vfazio/followers",
                "following_url": "https://api.github.com/users/vfazio/following{/other_user}",
                "gists_url": "https://api.github.com/users/vfazio/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/vfazio",
                "id": 5265893,
                "login": "vfazio",
                "node_id": "MDQ6VXNlcjUyNjU4OTM=",
                "organizations_url": "https://api.github.com/users/vfazio/orgs",
                "received_events_url": "https://api.github.com/users/vfazio/received_events",
                "repos_url": "https://api.github.com/users/vfazio/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/vfazio/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/vfazio/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/vfazio",
                "user_view_type": "public"
            },
            "commit_id": "6df947ec131f2de35c36359a1cdac20f961c641d",
            "commit_url": "https://api.github.com/repos/vfazio/pydantic/commits/6df947ec131f2de35c36359a1cdac20f961c641d",
            "created_at": "2024-06-12T14:55:12Z",
            "event": "referenced",
            "id": 13133318843,
            "node_id": "REFE_lADOABDGAc5n6c3nzwAAAAMOzoq7",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/13133318843"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2024-12-02T22:03:03Z",
            "event": "mentioned",
            "id": 15500017793,
            "node_id": "MEE_lADOABDGAc5n6c3nzwAAAAOb34CB",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/15500017793"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2024-12-02T22:03:03Z",
            "event": "subscribed",
            "id": 15500017806,
            "node_id": "SE_lADOABDGAc5n6c3nzwAAAAOb34CO",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/15500017806"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2025-02-11T09:08:45Z",
            "event": "demilestoned",
            "id": 16261017262,
            "milestone": {
                "title": "3.0.x"
            },
            "node_id": "DEME_lADOABDGAc5n6c3nzwAAAAPJO26u",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/16261017262"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2025-02-11T09:08:45Z",
            "event": "milestoned",
            "id": 16261017275,
            "milestone": {
                "title": "3.1"
            },
            "node_id": "MIE_lADOABDGAc5n6c3nzwAAAAPJO267",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/16261017275"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder",
                "user_view_type": "public"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2025-02-11T09:11:08Z",
            "event": "closed",
            "id": 16261058926,
            "node_id": "CE_lADOABDGAc5n6c3nzwAAAAPJPBFu",
            "performed_via_github_app": null,
            "state_reason": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/16261058926"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/5470/events",
    "html_url": "https://github.com/cython/cython/issues/5470",
    "id": 1743375847,
    "labels": [
        {
            "color": "444444",
            "default": false,
            "description": null,
            "id": 425553654,
            "name": "defect",
            "node_id": "MDU6TGFiZWw0MjU1NTM2NTQ=",
            "url": "https://api.github.com/repos/cython/cython/labels/defect"
        },
        {
            "color": "444444",
            "default": false,
            "description": null,
            "id": 425556315,
            "name": "Python Semantics",
            "node_id": "MDU6TGFiZWw0MjU1NTYzMTU=",
            "url": "https://api.github.com/repos/cython/cython/labels/Python%20Semantics"
        }
    ],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/5470/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": null,
        "closed_issues": 335,
        "created_at": "2019-02-24T14:21:23Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
            "events_url": "https://api.github.com/users/scoder/events{/privacy}",
            "followers_url": "https://api.github.com/users/scoder/followers",
            "following_url": "https://api.github.com/users/scoder/following{/other_user}",
            "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/scoder",
            "id": 491659,
            "login": "scoder",
            "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
            "organizations_url": "https://api.github.com/users/scoder/orgs",
            "received_events_url": "https://api.github.com/users/scoder/received_events",
            "repos_url": "https://api.github.com/users/scoder/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/scoder",
            "user_view_type": "public"
        },
        "description": "* Remove code for Python 2 and Python < 3.8.\r\n* Integrate better with Python 3.\r\n* Improve support for the Limited API.\r\n* Start supporting GIL-free Python 3.13.\r\n* Support the Py3.13 `sys.monitoring` API.\r\n* Support and use `am_send` for coroutines.",
        "due_on": null,
        "html_url": "https://github.com/cython/cython/milestone/65",
        "id": 4082235,
        "labels_url": "https://api.github.com/repos/cython/cython/milestones/65/labels",
        "node_id": "MDk6TWlsZXN0b25lNDA4MjIzNQ==",
        "number": 65,
        "open_issues": 20,
        "state": "open",
        "title": "3.1",
        "updated_at": "2025-02-11T09:11:32Z",
        "url": "https://api.github.com/repos/cython/cython/milestones/65"
    },
    "node_id": "I_kwDOABDGAc5n6c3n",
    "number": 5470,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 1,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 1,
        "url": "https://api.github.com/repos/cython/cython/issues/5470/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "state_reason": "completed",
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/5470/timeline",
    "title": "[BUG] Profiling/tracing fails in Py3.12",
    "updated_at": "2025-02-11T09:11:09Z",
    "url": "https://api.github.com/repos/cython/cython/issues/5470",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
        "events_url": "https://api.github.com/users/scoder/events{/privacy}",
        "followers_url": "https://api.github.com/users/scoder/followers",
        "following_url": "https://api.github.com/users/scoder/following{/other_user}",
        "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/scoder",
        "id": 491659,
        "login": "scoder",
        "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
        "organizations_url": "https://api.github.com/users/scoder/orgs",
        "received_events_url": "https://api.github.com/users/scoder/received_events",
        "repos_url": "https://api.github.com/users/scoder/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/scoder",
        "user_view_type": "public"
    }
}