{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "### Describe your issue\n\nThinking more about the `except *` in `nogil` performance pitfall. It's kind of hard to work around when calling 3rd party code that hasn't added exception specifications (even if you know they won't really raise exceptions).\r\n\r\nI propose a very localized `cython.call_with_legacy_noexcept(function(other_function()))` which only affects the function it directly wraps. In this example `other_function` would be called normally.\r\n\r\nI'm\r\n1. deliberately suggesting an ugly name\r\n2. making it as localized as possible (i.e. not even a decorator or a with block) to try to prevent it from being the standard boiler-plate that people copy (like `boundscheck(False)` ends up being). The intention is that you have to actively choose it.\r\n\r\nThis is potentially a bit of an issue if an exception is actually raised. However, it's no worse than setting `legacy_implicit_noexcept` set in setup.py (which I think applies it to every pxd file you use irrespective of how they were originally written). It's just aimed to be a way of working around these calls as locally as possible.",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/5604/comments",
    "created_at": "2023-08-08T19:35:02Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/5604/events",
    "html_url": "https://github.com/cython/cython/issues/5604",
    "id": 1841945891,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/5604/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOABDGAc5tyd0j",
    "number": 5604,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/cython/cython/issues/5604/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/5604/timeline",
    "title": "[ENH] Add a way to disable exception checks for a single function call",
    "updated_at": "2023-08-08T19:35:02Z",
    "url": "https://api.github.com/repos/cython/cython/issues/5604",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
        "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
        "followers_url": "https://api.github.com/users/da-woods/followers",
        "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
        "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/da-woods",
        "id": 10536947,
        "login": "da-woods",
        "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
        "organizations_url": "https://api.github.com/users/da-woods/orgs",
        "received_events_url": "https://api.github.com/users/da-woods/received_events",
        "repos_url": "https://api.github.com/users/da-woods/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/da-woods"
    }
}